### ISSUE TITLE
HTTParty::Response inspect raises exception on parse failure

### ISSUE THREAD

**Issue by thedanbob** [jnunemaker/httparty#150]
HTTParty was changed to use lazy parsing in [this commit](https://github.com/jnunemaker/httparty/commit/9fd5259c8dab00e426082b66af44ede2c9068f45).  As a result, some code that works normally will fail in the console.

For example, I have the following method: 

``` ruby
def sanity(url)
  HTTParty.get(url)
rescue MultiJson::DecodeError
  false
end
```

I called it in the console with a url that returned malformed JSON.  The get call succeeded, but then the console called inspect on the HTTPResponse object that was returned, which called the parser and raised a MultiJson::DecodeError.  Took me and my boss a while to figure out why the exception wasn't being caught by my method.

**Comment by GuyPaddock** [comment]
I'd like to point out that this one just bit us... we rescue a failed request and try to log the response we got back, but it turns out that `response.inspect` leads to... another exception! It would be nice if `inspect` on `Response` was able to rescue JSON failures.
