### ISSUE TITLE
adding default_data for data need to be send in the body for post

### ISSUE THREAD

**Issue by aliciatang** [jnunemaker/httparty#161]
My understanding of post is that all data is send in the body.
So if calling post the default_params should be merged together with query to body.

Right now default_params and :query are merged and constructed in the uri.

My suggest solutions:
since not all api server is smart enough to merger $_GET and $_POST together (some secure sites eg. paypal) will not allow any data in the uri when expecting POST. 
Adding something like default_data could be a nice feature to have so that we could put the username and password and secret there which are needed for every request.

**Comment by TheSmartnik** [comment]
The issue has been stale for awhile, closing this
