### ISSUE TITLE
SSL client certificates

### ISSUE THREAD

**Issue by JohnSmall** [jnunemaker/httparty#162]
The documentation on how to use HTTParty with SSL is completely absent. 

Here's what I need to do;-
We have a server we can make rest requests to, the server requires client certificates. I'm just learning this, but it seems the client certs can come in many forms, with and without passwords and such like. I'm using Firefox on a Mac, and I can backup my cert to a pk12 file, with a password, or export to a pem file, without a password.

Reading the code in HTTParty it seems that if I take the pem file option then I need to supply a password, and there's no option for feeding in a PK12 file.

How do I get this stuff to work?

**Comment by kurenn** [comment]
Hey @JohnSmall  I think you can do it with

```
class Client
    include HTTParty

    debug_output $stdout
    pkcs12 File.read("certs/filename.p12"), "123456"
end
```

I have been working with SSL for a client and I had troubles setting this up, there is not to much documentation out there, it would be good to have some...what a about a wiki article?

**Comment by kurenn** [comment]
I can add some documentation on how to achieve this...would be better to add a wiki article or on the main README?

**Comment by jnunemaker** [comment]
I would lean toward a docs/ folder with a markdown file. Then in the code or readme we can just link to that. Coolio?

**Comment by kurenn** [comment]
You can find the doc at https://github.com/jnunemaker/httparty/pull/449

**Comment by jji-fieldwire** [comment]
are people storing their certs in their repos and the passwords in env vars? or is there a better way of doing it
