### ISSUE TITLE
Add webcal to supported URI schemes?

### ISSUE THREAD

**Issue by allspiritseve** [jnunemaker/httparty#163]
I'm trying to parse a webcal feed, but HTTParty is complaining that the protocol is not HTTP or HTTPS. In the short term I can sub webcal with http but it seems like other text-based protocols like webcal or feed should be allowed.

**Comment by bklang** [comment]
It looks like this issue was fixed by #164 which was merged, so probably this should be closed as well.

**Comment by jnunemaker** [comment]
@bklang thanks!
