### ISSUE TITLE
Use bytesize instead of length to determine Content-Length

### ISSUE THREAD

**Issue by KidkArolis** [jnunemaker/httparty#206]
If body_json is a string that contains £ symbol, `Content-Length` header will be set incorrectly by HTTParty. See https://github.com/typhoeus/typhoeus, they handle that correctly.

```
response = HTTParty.post(endpoint,
  :headers => {
    'Content-Type' => 'application/json; charset=UTF-8'
  },
  :body => body_json
)
```

**Comment by TheSmartnik** [comment]
Pretty sure, back in the time, it was a problem with `Net/HTTP` in ruby 1.9.3. Since 2.0 `bytesize` is used to determine set `Content-Length `
