### ISSUE TITLE
Exception handling strategy when using httparty

### ISSUE THREAD

**Issue by bsingr** [jnunemaker/httparty#209]
Hey there!

I saw there are a few error classes defined in https://github.com/jnunemaker/httparty/blob/master/lib/httparty/exceptions.rb but there is no such thing as a global `HTTParty::Error` that allow a single rescue statement to catch up all possible errors when making requests with HTTParty. Instead I have to explicitely list all of the error classes defined by HTTParty.

Also I saw that these error classes are only used for special cases that occur within the HTTParty codebase and not for wrapping exceptions that occur in underlying libraries such as Net:HTTP.

Is there any reason for that I didn't see or would you appreciate me implementing a global error class and wrapping up exceptions from underlying libraries?

To clarify, I'd like to be able to do sth. like:

```
begin
  HTTParty.get('http://google.com')
rescue HTTParty::Error => e
  # handle e ...
end
```

Cheers
--dpree

**Comment by alanPaivaAsp** [comment]
This is not rescuing at all
