### ISSUE TITLE
Net::HTTPBadResponse: wrong status line: "<html>"

### ISSUE THREAD

**Issue by andrerpbts** [jnunemaker/httparty#216]
I'm getting an error, and I can't figure out why...

First of all, here is my code:

``` ruby
self.class.post('http://www.myexternalservice.com.br/ws_horarios/atualizaEscala', query: {empresa: dados[:empresa], func_escala: dados[:func_escala].to_json})
```

Here, the `dados` object, I have a hash, that is converted to json. 

It works, if I pass this JSON: https://gist.github.com/andrerpbts/5818575
There's two main nodes, but if I add another one, this won't work: https://gist.github.com/andrerpbts/5818593

Follow the debug trace I got: https://gist.github.com/andrerpbts/5818601

I tried to call it, using this JSON in another tool (see here: https://gist.github.com/andrerpbts/5818638) and worked fine.

My ruby is 1.9.3, using Rails 3.0.11, with Httparty version 0.11.0, on a Mac OSX 10.7.5.

Any suggestion? Thanks!

PS: This codes posted here won't work since I have edited some data to preserv my credentials.

**Comment by TheSmartnik** [comment]
It's been 5 years. Feels like it's ok to close this one 😅
