### ISSUE TITLE
URI::InvalidURIError for a URI that's not in my power to encode

### ISSUE THREAD

**Issue by kitsched** [jnunemaker/httparty#234]
I'm using httparty to unshorten short URIs and I happened upon:

`HTTParty.get('http://bit.ly/19NoFfn', limit: 50 )`

which when expanded yields:

`https://sublime.wbond.net/packages/PhpSpec Snippets`

which obviously throws a: URI::InvalidURIError.

Would it be possible to pass some parameter to httparty so that it would automatically try to encode URIs before trying to follow them?

**Comment by Rosa** [comment]
Have you considered to [use a different `uri_adapter`](https://github.com/jnunemaker/httparty/blob/87af97fced44df1de45495652ab66b5f8fe2dd29/lib/httparty.rb#L428) to parse the URL? I think `Addressable::URI` can deal with spaces in the URL, and other issues that doesn't work with `URI`:
```
> URI.parse(url)
URI::InvalidURIError: bad URI(is not URI?): https://sublime.wbond.net/packages/PhpSpec Snippets
> Addressable::URI.parse(url)
=> #<Addressable::URI:0x3febaa962410 URI:https://sublime.wbond.net/packages/PhpSpec Snippets>
```

**Comment by jnunemaker** [comment]
I'd definitely try a different uri adapter like @Rosa suggested.
