### ISSUE TITLE
HTTParty::Response#ok? Is not reliable

### ISSUE THREAD

**Issue by awls99** [jnunemaker/httparty#242]
Lets  say you  have  some code  that does this: 
last_response = HTTParty.get 'http://my/awsome/api/endpoint'
If you were to use a rest tool,  you could see it  returns no  content and http  204  code.
then you  have this object:

last_response.class
# =>  HTTParty::Response

last_response.code
# => 204

last_response.ok?
# =>  false

This  is misleading because any http code on the 2xx is OK  (and one could argue that 3xx are also ok).

Can't find where  this defined, so no pull  request  :(

**Comment by ben-burlingham** [comment]
If someone is looking for this later, there's a `.success?` method on the response object that seems to do what I'm looking for.
