### ISSUE TITLE
Response with Content-Encoding but empty body breaks

### ISSUE THREAD

**Issue by ghostganz** [jnunemaker/httparty#247]
I have a service that gives 304 Not Modified responses and has a response header "Content-Encoding: gzip" at the same time. (Arguably a bug in Rack::Deflate,  but that's another story).

Since the 304 response has no body, HTTParty chokes when trying to decompress the body:

```
httparty (0.12.0) lib/httparty/request.rb:272:in `initialize'
httparty (0.12.0) lib/httparty/request.rb:272:in `new'
httparty (0.12.0) lib/httparty/request.rb:272:in `handle_deflation'
httparty (0.12.0) lib/httparty/request.rb:106:in `perform'
httparty (0.12.0) lib/httparty.rb:486:in `perform_request'
httparty (0.12.0) lib/httparty.rb:423:in `get'
httparty (0.12.0) lib/httparty.rb:518:in `get'
...
```

The failing line in HTTParty:

```
body_io = StringIO.new(last_response.body)
```

**Comment by rusikf** [comment]
@ghostganz can you provide failing test for this issue ?

**Comment by jnunemaker** [comment]
I think https://github.com/jnunemaker/httparty/pull/530 closes this. Closing but let me know if I'm wrong.
