### ISSUE TITLE
I'd like to add "no proxy" option in connection method

### ISSUE THREAD

**Issue by tune** [jnunemaker/httparty#254]
I'm working behind proxy and my program need to access both the Internet and Intranet.
When accessing  Intranet, I need to set nil value to proxy setting because proxy server cannot handle the request to private address.

By 15ba0842f50e657ea5c0784efab5fd6ff19b8c88 commit, now it's impossible to pass nil value to Net::HTTP.new.
I'd like to add new option like "options[:http_noproxy]" to enable passing nil value.

**Comment by pic** [comment]
same problem here. @jnunemaker: I would much prefer if at
https://github.com/jnunemaker/httparty/blob/master/lib/httparty/connection_adapter.rb#L79
you have instead:
```if options.has_key?(:http_proxyaddr)```

Please take this into consideration, thx

**Comment by jnunemaker** [comment]
If someone wants to work up a PR that switches to key? and has tests I'm game.

**Comment by pic** [comment]
https://github.com/jnunemaker/httparty/pull/457

best
