### ISSUE TITLE
why use include HTTParty instead of extend?

### ISSUE THREAD

**Issue by timcharper** [jnunemaker/httparty#26]
As far as I can tell, the module HTTParty has no instance methods.  You include it, and it turns around and calls extend on a different module.  And then it sets class-level instance variables, class-level inheritable attributes, and so forth.

Is it just a personal preference?  What if we would prefer the module to operate on an instance level instead?  IE: instantianting an agent class that configures the httparty attributes.

Tim

**Comment by mbigras** [comment]
Hi there,

I came accross this issue while searching for a simpler way to pass username/password configuration into an HTTParty client.
It seems like HTTParty makes use of the concept of class methods.
Below is how I'm solving this problem but I'm not sure if it's the intended way to go about it:

```
class Client
	include HTTParty
	base_uri 'https://foo.bar.com/'
	default_options.update(verify: false)
	def initialize(config)
		self.class.basic_auth config['username'], config['password']
	end
end

config = YAML.load(File.read('config.yaml'))
client = Client.new(config['client']).class
```

I'd rather be able to write something like:

```
class Client
	include HTTParty
	base_uri 'https://foo.bar.com/'
	default_options.update(verify: false)
	def initialize(config)
		basic_auth config['username'], config['password']
	end
end

config = YAML.load(File.read('config.yaml'))
client = Client.new(config['client'])
```

But I get the error

```
some.rb:9:in `initialize': undefined method `basic_auth' for ...
```

Is my first implementation the intended way to pass configuration into an HTTParty client?
