### ISSUE TITLE
Setting `basic_auth` on `Base` doesn't get inherited

### ISSUE THREAD

**Issue by coreyward** [jnunemaker/httparty#276]
Similar to #83. Setting `basic_auth` in a `Base` class and inheriting from it in subclasses does not work. Issue exists in [Closeio](https://github.com/taylorbrooks/closeio) library:

```ruby
# as expected:
Closeio::Base.default_options
 => {:base_uri=>"https://app.close.io/api/v1", :basic_auth=>{:username=>"foo", :password=>""}, :headers=>{"Content-Type"=>"application/json"}, :parser=>HTTParty::Parser, :format=>:json} 

# unexpected, as described above:
Closeio::Lead.default_options
 => {:base_uri=>"https://app.close.io/api/v1", :basic_auth=>{:username=>nil, :password=>""}, :headers=>{"Content-Type"=>"application/json"}, :parser=>HTTParty::Parser, :format=>:json} 
```

Using v0.13.0.

**Comment by coreyward** [comment]
1. Set `basic_auth` on `Base`, e.g. `Base.default_options.merge! basic_auth: { ... }`. 
2. Subclass it, e.g. `class Lead < Base`
3. Inspect `default_options` on subclass, e.g. `Lead.default_options`. 

The default options should follow, but do not.

**Comment by jnunemaker** [comment]
I guess closing until we get something repeatable to prove there is an issue.

**Comment by coreyward** [comment]
Hmm, I wonder if it isn't a version issue, or perhaps because CloseIO [inherits from OpenStruct](https://github.com/taylorbrooks/closeio/blob/master/lib/closeio/base.rb#L2).
