### ISSUE TITLE
Handling exceptions

### ISSUE THREAD

**Issue by ghost** [jnunemaker/httparty#283]
How should I handle exceptions? For example timeouts, 404/500, without having to type my own error messages.

**Comment by gerrywastaken** [comment]
@jnunemaker: @ddevaal did follow your advice and posted his question to the group:
https://groups.google.com/forum/#!searchin/httparty-gem/500%7Csort:relevance/httparty-gem/FNsPCfXpcCc/sV8YhAklWwEJ
