### ISSUE TITLE
Setting the HTTParty.get method to timeout after ten seconds on a non-existent website?

### ISSUE THREAD

**Issue by sergiotapia** [jnunemaker/httparty#335]
Here's what I'm trying on a simple Rails app.

```
response = HTTParty.get('http://www.firebase.io', { timeout: 10 })
```

Obviously `http://www.firebase.io` does not exist, is there some way to set up this `.get` request to timeout after 10 seconds?

**Comment by bhaveshf-cuelogic** [comment]
So, for post request it will be as follows, correct ?

`HTTParty.post('http://www.firebase.io', body: params, timeout: 10)`

**Comment by BALOCH1** [comment]
Yes Set the default by:

```
module HTTParty
  default_timeout your_preferred_timeout
end
```

or set it individually by:

```
data = HTTParty.post("url",
  headers: {"Content-Type" => "application/json"},
  body: {update => true, first_name => "name"},
  timeout: your_preferred_timeout
)
```

**Comment by kingmt** [comment]
Will this return a response or will it throw an exception? If an exception which one?

When I am testing this I am getting an immediate exception of Errno::ECONNREFUSED instead of it timing out after 10 seconds

**Comment by vineeth-pradhan** [comment]
> Will this return a response or will it throw an exception? If an exception which one?

This throws `Net::OpenTimeout` exception after timeout

> When I am testing this I am getting an immediate exception of Errno::ECONNREFUSED instead of it timing out after 10 seconds

Timeout is subjective to the url you make request to. This doesn't look like something you can expect a timeout can do. You may be behind a firewall or require a request to 443 port
