### ISSUE TITLE
getaddrinfo: nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by jlerpscher** [jnunemaker/httparty#344]
Hi there,

Since few days, I have an error on my specs "getaddrinfo: nodename nor servname provided, or not known". When I run the same line in a console (same method, same url, same options) everything is fine. 

Any ideas?

Note: I recently upgraded to Yosemite

Source: http://github.com/jlerpscher/oztogo

**Comment by tholder** [comment]
I'm also seeing this, I don't know why yet.
