### ISSUE TITLE
What is the default timeout?

### ISSUE THREAD

**Issue by chris-gooley** [jnunemaker/httparty#351]
My apologies for the dumb question, but I haven't been able to find a default value for the timeout. Is there one? If so, what is it?

Thanks very much

**Comment by henrik** [comment]
To help future googlers: In Ruby 2.5.0, Net::HTTP has a default value of 60 seconds: https://docs.ruby-lang.org/en/2.5.0/Net/HTTP.html#attribute-i-read_timeout

**Comment by andxyz** [comment]
To help some more googlers:
Sometimes you can hit this when nothing is configured for Httparty, and the service you are trying to use is rate limiting you.

For instance, I ran into this default when I was posting too many messages to the slack api. In that case I was hitting an `open_timeout` not a `read_timeout`,

Both values default to 60 seconds. (I was on ruby 2.7 at the time)
https://docs.ruby-lang.org/en/2.7.0/Net/HTTP.html#attribute-i-open_timeout

**Comment by jaredbeck** [comment]
Also, be aware of `Net::HTTP.max_retries`, whose default is 1, and will thus retry once on timeout. To disable, set `max_retries: 0`, e.g.

```
# Net::ReadTimeout raised after 6s, not what you wanted ..
HTTParty.get('http://example.com', timeout: 3) 
# Net::ReadTimeout raised after 3s. This is what you wanted.
HTTParty.get('http://example.com', timeout: 3, max_retries: 0) 
```

See [discussion](https://github.com/jnunemaker/httparty/issues/755).
