### ISSUE TITLE
OpenSSL error with Version 13.3

### ISSUE THREAD

**Issue by rsnyder622** [jnunemaker/httparty#362]
The update from version 11 to 12 requiring SSL verification as a default has caused an issue.  Now when I try to use HTTParty to pull data, while setting up a correct ca file, I get:

OpenSSL::SSL::SSLError: SSL_connect reqturned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed.

I don't want to toggle off the verify on the get call but I'm not sure how else to get this to work.

**Comment by mcandre** [comment]
I'm getting this error when using the `gitlab` command line tool:

https://github.com/NARKOZ/gitlab/issues/116

What should I do?
