### ISSUE TITLE
HTTParty::Response it's not parsing correctly a response with a single boolean

### ISSUE THREAD

**Issue by facundofarias** [jnunemaker/httparty#372]
Today, I've been dealing more than 2 hours with HTTParty until I got this. 
This is the scenario: I have a very simple REST API, which returns a simple boolean, nothing else (as it can be seen on the attached image):
![image](https://cloud.githubusercontent.com/assets/2700564/5962686/d4115a2e-a7e5-11e4-9372-7684a9fd42e1.png)
In the request headers, nothing new:
![image](https://cloud.githubusercontent.com/assets/2700564/5962696/e68b01b4-a7e5-11e4-9c4f-9089406ab208.png)
The thing is this: On the rails side, this variable doesn't get parsed as a Boolean, and it is received as a HTTParty::Response object. What I had to do was, casting it to a string (using .to_s), and then evaluate that variable. Is this the expected behavior? I would expect a Boolean directly, but.. I don't know, maybe is there a reason behind this?

Thanks a lot

**Comment by jnunemaker** [comment]
Can you include the calls you were making or a short script to demo the issue?

**Comment by facundofarias** [comment]
This is the method that I am doing: 
```
def self.login(request)
    post("/api/test", {:body => request.to_json , :headers => {"Content-Type" => "application/json; charset=UTF-8"}})
end
```
Then I am storing the returned value into a variable. Do you need something else?

**Comment by jnunemaker** [comment]
HTTParty only parses as json if the server it hit has application/json in the content type. Could you show an example curl or something of the full response from the server?

**Comment by facundofarias** [comment]
The Content-Type was application/json, but the thing was that.. the body was only a "true" or "false" value, which it's not a JSON valid value.
