### ISSUE TITLE
NameError: uninitialized constant HTTParty::BasicObject

### ISSUE THREAD

**Issue by rusikf** [jnunemaker/httparty#373]
```ruby 
httparty$ pry
[1] pry(main)> require './lib/httparty'
NameError: uninitialized constant HTTParty::BasicObject
from /home/ruslan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/httparty-0.13.3/lib/httparty/response.rb:2:in `<module:HTTParty>'
```
Only when i include httparty this way, error appears, i think we must have more elegant solution that BasicObject to prevent namespace pollution, but it don't know it, @jnunemaker  what you think about it?

**Comment by jnunemaker** [comment]
We can probably just use basic object and remove our hack since we can drop 1.8 support.

**Comment by jnunemaker** [comment]
Now just using basic object I believe so this can be closed.
