### ISSUE TITLE
ArgumentError: Gem sources must be absolute. You provided 'build.httparty/'

### ISSUE THREAD

**Issue by scarver2** [jnunemaker/httparty#375]
I'm having an issue bundle installing httparty. 

I'm running Bundler version 1.8.1 and Ruby 2.2.0. As an avid user of HTTParty, I'm quite confident that the issue is the gemspec file not being compatible with the new bundler since I've not encountered this issue before.

Here is the bundler log output:

```
ArgumentError: Gem sources must be absolute. You provided 'build.httparty/'.
An error occurred while installing httparty (0.13.3), and Bundler cannot continue.
Make sure that `gem install httparty -v '0.13.3'` succeeds before bundling.
```

and yes, `gem install httparty -v '0.13.3'` works flawlessly.

**Comment by mkonecny** [comment]
This is a known issue that was introduced with bundler 1.8.1 today: https://github.com/bundler/bundler/issues/3398

For now you can revert to bundler 1.8.0

**Comment by scarver2** [comment]
Thank you for the info @mkonecny

I performed a `gem uninstall bundler` and issued a `gem install bundler -v '1.8.0'`  All is well now.

**Comment by jkatsnelson** [comment]
Thanks for this!

**Comment by glpunk** [comment]
Excellent! thank you, downgrade bundler version help me to fix this error:

ArgumentError: Gem sources must be absolute. You provided 'build.http_parser.rb/'.
An error occurred while installing http_parser.rb (0.6.0), and Bundler cannot continue.
Make sure that `gem install http_parser.rb -v '0.6.0'` succeeds before bundling.

**Comment by macha3162** [comment]
Thanks for this!

**Comment by kovyrin** [comment]
So, does this mean httparty is not going to work on any bundler versions past 1.8.x?

**Comment by mkonecny** [comment]
@kovyrin no, it was a bug in 1.8.1 only. 1.8.2 fixed it.
