### ISSUE TITLE
Redirect URL is broken if trailing / is missing

### ISSUE THREAD

**Issue by DarthMax** [jnunemaker/httparty#377]
It seems that the automatic redirect calculates the wrong url if the trailing slash is missing in the original url. 

```ruby
class DebugParty
  include HTTParty
  debug_output $stdout 
end 

DebugParty.get("http://vaximm.com")
#opening connection to vaximm.com:80...
#opened
#<- "GET / HTTP/1.1\r\nConnection: close\r\nHost: vaximm.com\r\n\r\n" 
#-> "HTTP/1.1 302 Found\r\n" 
#-> "Date: Thu, 26 Feb 2015 17:32:40 GMT\r\n" 
#-> "Content-Type: text/html\r\n" 
#-> "Content-Length: 0\r\n" 
#-> "Connection: close\r\n" 
#-> "Location: deutsch/\r\n" 
#-> "Server: UD Webspace 3.0\r\n" 
#-> "\r\n" 
#reading 0 bytes...
#-> "" 
#read 0 bytes
#Conn close
#opening connection to vaximm.comdeutschdeutsch:80...

```

Here the redirect URL is `vaximm.comdeutschdeutsch` instead of `vaximm.com/deutsch`.
When using `DebugParty.get("http://vaximm.com/")` every thing is fine.
Nevertheless in my understanding http://vaximm.com is a valid url and should therefore work aswell.

**Comment by jnunemaker** [comment]
Seems like this is maybe related to relative redirects. Since you don't supply the "/" at the beginning and it is not in the url, it struggles. I'd be open to a pull that checks if the path is "" and adds "/" for relative redirects if anyone has time to tackle it right now.
