### ISSUE TITLE
Not follow redirect and get redirect response code

### ISSUE THREAD

**Issue by pisaacs** [jnunemaker/httparty#380]
With using `HTTParty.head` is there an option for disabling redirects and obtaining the response code (checking specifically for 301/302)?

**Comment by xunker** [comment]
Yes, you can pass `follow_redirects: false`. Example:

```ruby
response = HTTParty.head(url_that_returns_redirect, follow_redirects: false)
response.code
# => 302
```

**Comment by pisaacs** [comment]
Thank you @xunker!

**Comment by dmitrydanilich** [comment]
thank you @xunker , helped me a lot with this one, tried to use "no_follow: true" at first, but got this "HTTP redirects too deep (HTTParty::RedirectionTooDeep)", then tried yours - and voilà!
