### ISSUE TITLE
response.class and response.instance_of?

### ISSUE THREAD

**Issue by CBluowei** [jnunemaker/httparty#381]
```ruby
response = Httpaty.get(url)

response.class #==> HTTParty::Response,

#but...

response.kind_of?(HTTParty::Response) #==> false
response.kind_of?(Hash) #==> true
```

why do I get this case??

**Comment by wolfascu** [comment]
This is due to the way [`HTTParty::Response` implements `method_missing`](https://github.com/jnunemaker/httparty/blob/2d2779e7555f2a0927d79ba7fdb37921c3310dd9/lib/httparty/response.rb#L65).

The call to `method_missing` is delegated to the internal `parsed_response` and `response` objects. The former is a `String`, and it's the one that responds to `is_a?`/`kind_of?`.

Therefore, 

```ruby
response.kind_of? String #===> true
```

**Comment by jnunemaker** [comment]
@wolfascu is correct. Its an awkward part of httparty due to keeping backwards compatibility when we added lazy parsing.

**Comment by JonMidhir** [comment]
Is there anything to be said for implementing `HTTParty::Response#is_a?`? I ran into this as well and it caused a bit of a problem. I'm happy to issue the PR of course.

**Comment by cameronwp** [comment]
I ran into this bug yesterday and it was super confusing. IMO, backwards compat should not outweigh meeting reasonable expectations for the behavior `instance_of?` / `kind_of?` / `is_a?`. I'd definitely +1 an effort to fix this.

**Comment by JonMidhir** [comment]
@cameronwp I actually addressed this in https://github.com/jnunemaker/httparty/pull/444 but it's a bit of a hack tbh.

Ultimately anything to get around the `method_missing` override is going to be, though.

I'd started work a while back to refactor this whole class and remove the override. I can perform some necromancy on that if the maintainers think it's worthwhile. Would end backwards compatibility but we could put an update message in the gemspec to warn.

/cc @jnunemaker

**Comment by cameronwp** [comment]
My mistake! Looks like we've been using v0.13.7.

**Comment by jnunemaker** [comment]
@JonMidhir any thoughts on an option for this that people can opt into? Maybe also a deprecation warning and then eventually we flip flop the option? That seems like an ok path forward. HTTParty is used a lot, so I'm not sure I'm comfortable with only a message in the changelog or what not.

**Comment by JonMidhir** [comment]
@jnunemaker Yeah you're right, it's a bit much to force people to refactor immediately. I'll put a PR together as a starting point. Reckon a post install message and something in the Readme will be enough to alert people to the new option?

**Comment by jnunemaker** [comment]
@JonMidhir I'd avoid the post install. The changelog/history file (which I need to update) should be enough if we can deprecate and let people move slowly.

**Comment by JonMidhir** [comment]
@jnunemaker Grand. I'll come back in a few days with a PR and we can take it from there.

**Comment by JonMidhir** [comment]
Glad to have made a start on this. I went back to first principles as the class has changed a bit since I last looked at it. 

I'm not sure if it's being made obvious enough to the user how to address the deprecation notice but happy to take guidance.

**Comment by vergenzt** [comment]
Happened to stumble upon this thread, but FWIW isn't this generally the use case for major version bumps? If HTTParty has been in use for this long and you're worrying about backcompat might it be worth it to just cut a 1.0 to indicate breakages of backcompat?
