### ISSUE TITLE
Allow setting directly POST data without changing URI

### ISSUE THREAD

**Issue by deric** [jnunemaker/httparty#382]
I'd like to rewrite following `Net:HTTP` code into `httparty`, is it possible? I have a hash of values (e.g. `opts = {key1: 'foo', key2: 'bar'}`) that I'd like to include in POST body.

```ruby
require 'net/https'
require 'uri'
uri = URI.parse("http://example.com/api/resource")
http = Net::HTTP.new(uri.host, uri.port)
request = Net::HTTP::Post.new(uri)
request.set_form_data(opts)
response = http.request(request)
```
This would change the content type to: `"content-type"=>["application/x-www-form-urlencoded"]`.
Or I could rewrite last 2 lines and set directly POST data, with mine "encoding":
```ruby
request.body = "key1=foo&key2=bar"
response = http.request(request)
```

With `httparty` is looks much easier:
```ruby
opts = {
  body: {
    key1: 'foo',
    key2: 'bar',
  },
}
post("http://example.com/api/resource", query: opts)
```
However this would change the requested URI into something like this: `http://example.com/api/resource&body=key1%3Dfoo%26key2%3Dbar`. This is a valid approach if the POST data are small enough (don't exceed 2048 characters). In my case I have to sign each request URI with all parameters with SHA-1, thus changing URI before sending request is unacceptable.

This issue might be related to #161

**Comment by kremez19** [comment]
If you want to put query data directly into POST body, you should change your code to use body root key instead query key like here:
```ruby
opts = {
    key1: 'foo',
    key2: 'bar',
}
post("http://example.com/api/resource", body: opts)
```
or
```ruby
opts = {
  body: {
    key1: 'foo',
    key2: 'bar',
  },
}
post("http://example.com/api/resource", opts)
```

**Comment by deric** [comment]
I can't see how that solves the issue. It would still change the requested URI. With this one:
```ruby
opts = {
  body: {
    key1: 'foo',
    key2: 'bar',
  },
}
```
I'll get `http://example.com/api/resource?body[key1]=foo&body[key2]=bar`, with the other one:
```ruby
opts = {
    key1: 'foo',
    key2: 'bar',
}
```
I'll get `http://example.com/api/resource?key1=foo&key2=bar`. But content is still send via URI and not within POST body.

**Comment by kremez19** [comment]
Are you sure? How do you debug it? I found in code that if we use :body key it put data into request body. https://github.com/jnunemaker/httparty/blob/master/lib/httparty/request.rb#L129
I debuged like in #161 issue exapmle with debug_output

**Comment by deric** [comment]
All right, I got it. I was still nesting the hash under `query`. Providing some example of POST request in README would be nice, this is quite basic stuff.
