### ISSUE TITLE
Multiple `Set-Cookie` headers aren't respected in the response

### ISSUE THREAD

**Issue by besi** [jnunemaker/httparty#384]
My server issues multiple `Set-Cookie` directives in my Response:

``` http
HTTP/1.1 302 Found
Date: Mon, 23 Mar 2015 18:24:11 GMT
Server: Apache
Pragma: no-cache
Set-Cookie: Navajo=3wJATUguEoQWBd0-; Domain=.server.com; Path=/; Secure; Version=1; HttpOnly
Set-Cookie: TimeoutLoggedIn=login; Domain=.agate.ch; Path=/; Secure; Version=1; HttpOnly
Connection: close
Location: https://server.com/something
Cache-Control: no-cache
Expires: Thu, 1 Jan 1970 00:00:00 GMT
Content-Length: 285
Content-Type: text/html; charset=utf-8
Set-Cookie: BITD-Persistence=1638274978.47873.0000; path=/
```

So I have the following three cookies:

``` http
Set-Cookie: TimeoutLoggedIn=login; Domain=.agate.ch; Path=/; Secure; Version=1; HttpOnly
Set-Cookie: Navajo=3wJATUguEoQWBd0-; Domain=.server.com; Path=/; Secure; Version=1; HttpOnly
Set-Cookie: BITD-Persistence=1638274978.47873.0000; path=/
```

Now when I check my header variable, there is only the last entry left:

``` ruby
response = HTTParty.get(login_url, :basic_auth => auth)
puts response.headers['set-cookie']
```
### Expected results

I would expect to either get an array back or to get the cookies merged together in one `set-cookie` call. 

Alternatively I would be happy (enough) to get the raw response header, so that I can parse the individual cookies myself.

**Comment by besi** [comment]
According to <http://tools.ietf.org/html/rfc6265#section-4.1.2> it is perfectly fine to have multiple `set-cookie`s:

>    Origin servers **SHOULD NOT fold multiple Set-Cookie header fields** into
   a single header field.  The usual mechanism for folding HTTP headers
   fields (i.e., as defined in [RFC2616]) might change the semantics of
   the Set-Cookie header field because the %x2C (",") character is used
   by Set-Cookie in a way that conflicts with such folding.

**Comment by jnunemaker** [comment]
The only question I have then is whether this is in net/http or httparty. I'd probably make the same request using only net/http and see if it returns array as expected.

**Comment by besi** [comment]
I get the expected result when using net/http:

```ruby
url = URI(login_url)
req = Net::HTTP::Post.new(url.request_uri)
req.basic_auth user, pw
http = Net::HTTP.new(url.host, url.port)
http.use_ssl = (url.scheme == "https")
response = http.request(req)
puts response.get_fields('set-cookie')
```

The result now contains all three entries

    Navajo=AMjSm...g4-; Domain=.server.com; Path=/; Secure; Version=1; HttpOnly
    TimeoutLoggedIn=login; Domain=.server.com; Path=/; Secure; Version=1; HttpOnly
    BITD-Persistence=1638274978.47873.0000; path=/

**Comment by besi** [comment]
**Sidenote**: `net/http` provides two ways to access the cookies:

```ruby
# As array
response.get_fields('set-cookie')

# As string which concats the cookies with `, `
response['Set-Cookie'] 
´´´

**Comment by jnunemaker** [comment]
> Sidenote: net/http provides two ways to access the cookies:

Yeah, that is what I was curious about. I would assume we are using the bracket notation but haven't looked.

**Comment by linrock** [comment]
HTTParty correctly handles multiple Set-Cookie headers. For example:

```python
import SimpleHTTPServer

class RequestHandler(SimpleHTTPServer.SimpleHTTPRequestHandler):

    def do_GET(self):
        if self.path == "/":
            self.send_response(302)
            self.send_header("Set-Cookie", "A=1")
            self.send_header("Set-Cookie", "B=2")
            self.send_header("Location",   "/2")
        elif self.path == "/2":
            self.send_response(302)
            self.send_header("Set-Cookie", "C=3")
            self.send_header("Set-Cookie", "D=4")
            self.send_header("Location",   "/3")
        else:
            self.send_response(200)
            self.send_header("Set-Cookie", "E=5")
            self.send_header("Set-Cookie", "F=6")

if __name__ == '__main__':
    SimpleHTTPServer.test(HandlerClass=RequestHandler)
```

When following redirects (301, 302) with HTTParty, accessing `response.headers['set-cookie']` only gives you the cookies set by the final response. 

```ruby
response = HTTParty.get "http://localhost:8000"
puts response.headers['set-cookie']
# => E=5, F=6
```

To grab all the cookies, you'll have to merge the cookies captured from the redirects with the cookies set by the final response.

```ruby
cookies = HTTParty::CookieHash.new
cookies.add_cookies response.request.options[:headers]["Cookie"]
cookies.add_cookies response.headers['set-cookie']
puts cookies
# => {:A=>"1", :B=>"2", :C=>"3", :D=>"4", :E=>"5, F=6"}
```

**Comment by jnunemaker** [comment]
So perhaps with https://github.com/jnunemaker/httparty/issues/384#issuecomment-160465274, this is good to close. Correct me if I'm wrong.

**Comment by sudostack** [comment]
This is a case that isn't common, but would still be nice to note in the documentation. Since headers are often passed to one of the API methods as a hash, enforcing key uniqueness, am I right in saying that there isn't an example that shows how this can be achieved?
