### ISSUE TITLE
New release on RubyGems needed to address URI.escape is obsolete

### ISSUE THREAD

**Issue by mrjcleaver** [jnunemaker/httparty#389]
https://rubygems.org/gems/httparty shows:

````
VERSIONS:
0.13.3 - November 6, 2014 (74 KB)
````

Yet https://github.com/jnunemaker/httparty/issues/281 although fixed in master is a problem for anyone using the RubyGems version of this gem.

**Comment by oversee-ffleming** [comment]
Agreed - a new release would be lovely

**Comment by mrjcleaver** [comment]
Thank you so much for releasing this. Sorry to have had to be such a pain about it!
