### ISSUE TITLE
After request hooks

### ISSUE THREAD

**Issue by 23tux** [jnunemaker/httparty#392]
Hi,

when I have HTTParty included in my class, is it possible to run a piece of code like an after hook, that performs some checks on the response?

Background: I have a class with a lot of methods, and I want to check if the `response.code` is an unauthorized 401 or a permission denied 403. It would lead to a lot of code duplication, if I had to call a method that is given the response from a get or a post request, and checks if the code is right.

I tried it with a block as third argument, but the block only gets the response body.

**Comment by jnunemaker** [comment]
There is not. I typically just make my own class that wraps httparty and does this. Hooks like this can add a lot of slowness to libraries in my experience, even when they aren't used.
