### ISSUE TITLE
Error on SSL requests

### ISSUE THREAD

**Issue by resistorsoftware** [jnunemaker/httparty#393]
Ruby 2.2.1, latest httparty gem

My base_uri is 'https://myurl.com'

When I do a basic GET like

    get({ 'data' => 'foo' })

the response is

    Errno::ECONNREFUSED: Connection refused - connect(2) for nil port 80

But if I just substitute a plain string in as 

    get('https://myurl.com?data=foo') it works like a peach... 

I am confused... why the problem with one technique?

**Comment by jnunemaker** [comment]
This should work:

```
get('/', query: {'data' => 'foo'})
```

get always requires a string path:
https://github.com/jnunemaker/httparty/blob/3b12131e0e0ddda8224615eb37d7e963c6b4b427/lib/httparty.rb#L460

**Comment by resistorsoftware** [comment]
Thanks..  Made an error
Should have been 
    get('/service', query: { 'data' => 'foo' })

In my example. Turns out true culprit was a typo on a key param and a slash in the uri string that was url encoded.

**Comment by s2t2** [comment]
setting `base_uri = "https://myurl.com/"` instead of `base_uri "https://myurl.com/"` will also produce this error. to fix, remove the equals sign in `base_uri` declaration.

**Comment by macmartine** [comment]
@s2t2 You da man!

**Comment by jonnymacs** [comment]
@s2t2 yes, thnk you.  spared me many more minutes of misery
