### ISSUE TITLE
http does not accept registry part

### ISSUE THREAD

**Issue by PaquitoSoft** [jnunemaker/httparty#394]
Hi there!

I'm using HTTParty in a project involved with podcasts management and found a problem we don't know how to solve but using another http requester (which we don't want).

Requesting this URL (http://svd_identity.spinninpodcasts.com/rss) raises this error:
```
ruby-2.0.0-p353/lib/ruby/2.0.0/uri/generic.rb:214:in `initialize': the scheme http does not accept registry part: svd_identity.spinninpodcasts.com (or bad hostname?) (URI::InvalidURIError)
```
[Here](http://stackoverflow.com/questions/5208851/is-there-a-workaround-to-open-urls-containing-underscores-in-ruby) they say it's a problem with the use of _URI.parse_.
Does HTTParty have any alternative?

Thanks.

**Comment by jnunemaker** [comment]
> Does HTTParty have any alternative?

It does not. I've never came across this.  Looks like addressable supports underscores:

```
irb(main):001:0> require "addressable/uri"
=> true
irb(main):002:0> Addressable::URI.parse "http://svd_identity.spinninpodcasts.com/rss"
=> #<Addressable::URI:0x3fd8be0213a0 URI:http://svd_identity.spinninpodcasts.com/rss>
irb(main):003:0> 
```

I'll leave the issue open for now. It seems like it would not be too hard to make URI replaceable for Addressable::URI. I'd be open to a tested PR.
