### ISSUE TITLE
HTTParty not respecting the no_proxy environment variable

### ISSUE THREAD

**Issue by fgimian** [jnunemaker/httparty#397]
Hey there guys, really love your library :smile: 

I've noticed a strange behaviour which is easily reproducible on a system which uses a proxy to get out to the internet.

I've setup my proxy and an exceptions list as follows:

```bash
export http_proxy=http://127.0.0.1:3128
export https_proxy=http://127.0.0.1:3128
export no_proxy=.internal.domain.com
```

Now performing a basic HTTP request to the internal domain with HTTParty simply hangs and waits forever while the same test with curl, wget or Python requests works as expected.

The same problem seems to occur with `Net::HTTP` so perhaps this is outside the scope of your project.  Another related report can be found here: https://github.com/berkshelf/berkshelf/issues/1341

Any ideas?
Fotis

**Comment by jnunemaker** [comment]
If it also occurs with net/http then that is the root issue. Probably nothing we can do in httparty.

**Comment by fgimian** [comment]
Would you folks consider support [httpclient](https://github.com/nahi/httpclient) which supports `no_proxy` properly? :smile:

**Comment by jnunemaker** [comment]
I'm not interested in turning httparty into something that supports multiple lower level drivers. Faraday does though, so perhaps you would get more mileage using faraday?

**Comment by fgimian** [comment]
I understand your position.  The API in HTTParty is awesome and my favourite of the bunch, but I'll check out the others or maybe even consider using httpclient directly.

It's a huge shame that the core Net::HTTP library has this problem as it's a major problem for us extending beyond HTTParty to other modules which use it too.

Thanks for your reply
Fotis

**Comment by jnunemaker** [comment]
> It's a huge shame that the core Net::HTTP library has this problem

Yeah, that is too bad.
