### ISSUE TITLE
Undefined method base_url

### ISSUE THREAD

**Issue by quantumpotato** [jnunemaker/httparty#407]
Fresh install of Rails 4.2 and HTTParty.

irb(main):001:0> SummonerValidator
NoMethodError: undefined method `base_url' for SummonerValidator:Class

class SummonerValidator
	include HTTParty

	def api_key
	end

  def initialize(service, page)
    @options = { query: {site: service, page: page} }
  end

end

just loading SummonerValidator in my rails console gives me the error.

Why is this happening?

**Comment by jnunemaker** [comment]
Please post questions/unconfirmed bugs to the mailing list:
https://groups.google.com/forum/#!forum/httparty-gem

Also, I'd recommend creating a small reproducible script. The information provided makes it pretty hard to debug as it could just be something with your rails setup.
