### ISSUE TITLE
Parser error raised immediately prevents access to response details

### ISSUE THREAD

**Issue by GeReV** [jnunemaker/httparty#421]
I'm currently working with a slightly *problematic* HTTP API, which on occasion returns non-JSON responses on errors.
I.e. a 500 error with a simple "not available" plaintext response.

Such a case raises a `JSON::ParserError` and hides away details that could be relevant for error handling, such as the status code returned:

```ruby
begin
  response = HTTParty.get('url.json', ...) # Raises a JSON::ParserError
rescue
  # response is unavailable to check response.code
end
```

I think a solution for this would be to perform the parsing lazily, when first trying to access `parsed_response` or any other data that is actually derived from the body.

An example for such a use case:
```ruby
response = HTTParty.get('url.json', ...) # Does not raise an exception

puts response.code # response.code is available

begin
  response.parsed_response # Raises the parser exception here
resuce
  ...
end
```

**Comment by jnunemaker** [comment]
What version are you on? Pretty sure that parsing is lazy.

https://github.com/jnunemaker/httparty/blob/78da14d4f6ccae82f7727f2d682e117713fdb9d0/lib/httparty/request.rb#L289
https://github.com/jnunemaker/httparty/blob/78da14d4f6ccae82f7727f2d682e117713fdb9d0/lib/httparty/response.rb#L22-L24

**Comment by GeReV** [comment]
I am currently on version 0.13.3. Was this added at a later point?

**Comment by jnunemaker** [comment]
It should be in 0.13. I see the psuedo code, but any chance you could provide a small script that show the error to be sure it is httparty and not something in your app? Thanks!

**Comment by GeReV** [comment]
I managed to get the following to throw:
```ruby
HTTParty.get('http://getstatuscode.com/503', headers: { 'Content-Type' => 'application/json' }, format: :json)
```

Looks like I forgot to add the `format: :json` bit. :\

**Comment by jnunemaker** [comment]
I put this into testing.rb:

```ruby
require "rubygems"
require "httparty"

response = HTTParty.get('http://getstatuscode.com/503', headers: { 'Content-Type' => 'application/json' }, format: :json)
p response.code

begin
  response.parsed_response
rescue => exception
  p 'bombed'
  p exception.class
end
```

I then ran it:

```
$ ruby testing.rb 
503
"bombed"
JSON::ParserError
```

That was on 0.13.5, but I would think any 0.13 would be fine. Note that if you do anything in irb it will bomb as irb calls inspect and Response#inspect calls parsed body.

**Comment by henrik** [comment]
I'm seeing what I think is the same issue. I'm using httparty 0.17.0.

Repro in RSpec with webmock:

```
describe "Example" do
  it "shows the issue" do
    stub_request(:post, "https://example.com/hello").and_return(status: 123, body: "Nooooo")

    response = HTTParty.post("https://example.com/hello", format: :json)

    p response.code  # This outputs fine.
    p response  # This raises JSON::ParserError, "unexpected token at 'Nooooo'"
  end
end
```

@jnunemaker, I'm not sure I understand your comment just above. Are you saying that `response.inspect` causing a `JSON::ParserError` is not considered a bug?

I'm thinking it could be useful for debugging if you could inspect responses when they went wrong, without this slightly cryptic error message. The code I'm looking at now shows response details when things go wrong, for example. Being able to use `inspect` to get those details would be convenient.

**Comment by henrik** [comment]
Ran into this again today with some other code that essentially raises an error message including `response.inspect` if the response code is not the expected one. I grepped and we seem to have another few instances of this.

@jnunemaker I'd be happy to attempt a PR to address this if you're open to it :)
