### ISSUE TITLE
Error performing a delete with query params on base uri

### ISSUE THREAD

**Issue by Amooti** [jnunemaker/httparty#423]
When I perform delete with just the base_uri (i.e., delete('', query: {foo: 'bar'}), the parameter parsing sets path to 'bar'.

**Comment by jnunemaker** [comment]
Can you provide a small script demonstrating your issue that I can run?

**Comment by francistm** [comment]
Maybe @Amooti is talking about something like below.

``` ruby
class Foo
  include HTTParty
  base_uri 'www.example.com'

  def perform_delete
    self.class.delete '', query: { foo: 'bar' }
  end
end


Foo.new.perform_delete.request.last_uri.to_s
```

Even this will return `http://www.example.com?foo=bar`, but looks it works fine and able to get the content.

btw, why not use `self.class.delete '/', query: { foo: 'bar' }` instead an empty path?

**Comment by jnunemaker** [comment]
Yeah I think passing '/' is fine. Not sure why an empty path would be passed. If someone can verify this and make a PR I would be happy to merge.
