### ISSUE TITLE
Stripe's API requires duplicate json keys

### ISSUE THREAD

**Issue by RichardGrossman** [jnunemaker/httparty#425]
HTTParty:

:body => [ { "amounts[]" => '10', "amounts[]" => '24' } ].to_json,

#-->  warning: duplicated key at line 50 ignored:

Curl handles it like this:

-d amounts[]='14'       -d amounts[]='26'

Any suggestions while we wait for Stripe to stop demanding invalid JSON in their request?

**Comment by jnunemaker** [comment]
Odd. I don't have any off the top of my head. Perhaps hit up the mailing list and maybe someone there has hit it. Closing here as not really an httparty issue. The httparty mailing list is on google groups, just search for it.
