### ISSUE TITLE
HTTParty::Response being truthy 

### ISSUE THREAD

**Issue by Bartuz** [jnunemaker/httparty#426]
I'm not done with investigation yet but really interesting things are happening here. 

What exactly happened? I'm a bit confused but let me explain ...:

my method consists of:
```
def something
  response = get("https://conservatives.com", timeout: 2, verify: false)
  return unless response
  respone.crazy_methods
  respone.more_crazy_methods
end
```

during execution I had: `NoMethodError: undefined method `crazy_method' for nil:NilClass`

So `respone.crazy_methods` was executed even though `return unless response` was above. Let's double check it:

```
[88] pry(Checker::Website)> response || "response is false"
=> nil
```

Okey, so it means `response` is truthy. or... is it?

```
[6] pry(Checker::Website)> response
=> nil
[7] pry(Checker::Website)> response.nil?
=> true
[11] pry(Checker::Website)> response.present?
=> false
```

how nil can be truthy?

```
[97] pry(Checker::Website)> response.class
=> HTTParty::Response
```

This is how.

What's going on here? With help from @marcindobry we found this line a bit missleading

https://github.com/jnunemaker/httparty/blob/master/lib/httparty/response.rb#L67
```
 def method_missing(name, *args, &block)
      if parsed_response.respond_to?(name)
        parsed_response.send(name, *args, &block)
      elsif response.respond_to?(name)
        response.send(name, *args, &block)
      else
        super
      end
    end
```

let's check what's parsed_response:

```
[100] pry(Checker::Website)> response.parsed_response
=> nil
[101] pry(Checker::Website)> response.parsed_response.class
=> NilClass
```

there we go.

Temporary solution: use `response.present?`.

While I was debugging it I found other really strange behaviour:

```
[102] pry(Checker::Website)> response.class
=> HTTParty::Response
[103] pry(Checker::Website)> response.class.superclass
=> BasicObject
```

So it's a non-system-object which doesn't inherit from Object. Sounds dangerous.

I found it all happened here:
https://github.com/jnunemaker/httparty/commit/9a27bf96ed49f6c540e7450ff845b97403769f80

What's the reason I would ever want to skip inheriting from `Object`? 

Also I got curious why `response` answers to `.class` and `.superclass` even though ancestors don't include Object

```
response.class.ancestors
=> [HTTParty::Response, BasicObject]
```
But I migrated discussion on [stackoverflow](http://stackoverflow.com/questions/31831828/why-does-basicobject-answer-methods-superclass-and-class)

**Comment by jnunemaker** [comment]
This is an old backwards compatible thing. There was a time when httparty just returned the parsed body. This meant you couldn't get at the status code, headers, etc. I added this shim to allow setting the response code and more while still allowing it to behave like it was just an array or a hash. The only issue is using it for truthy checks, which I'm not a fan of anyway. If you want to test something, test it, don't rely on ruby returning truthy. Use .nil? or .present? as it will always work. When I say you, I just mean "the programmer in general", not you specifically. :) If I would have changed httparty to return a real response object say with a data method that returned the parsed body, I could have avoided inheriting from basic object and all would have been well, but that would have broken everyone's code, and I didn't want to do that. Hope that explains it all.

**Comment by suryapandian** [comment]
response.present?
gives me 
`NoMethodError: undefined method `present?' for #<HTTParty::Response:0x007ff3c98cd0b0>`

This is the code that I am trying

`require 'httparty' 
response = HTTParty.get('https://www.google.com')
puts "HERE IS THE STATUS : #{(response.present? && response.success?)}"`

**Comment by Bartuz** [comment]
.Present? Comes with active support (which is included with rails).

W dniu pt., 7.06.2019 o 09:07 Surya <notifications@github.com> napisał(a):
