### ISSUE TITLE
NoMethodError: undefined method `debug_output' for ...

### ISSUE THREAD

**Issue by tilo** [jnunemaker/httparty#428]
NoMethodError: undefined method `debug_output' for #<Device:0x007fed0ad2f5b0>

but Device is not the class where HTTParty is included into, and where debug_output is specificed.

**Comment by jnunemaker** [comment]
Can you re-open with more information? I'll need to see the code you are using in order to be able to help. It seems like you are passing the wrong type of object to debug_output.
