### ISSUE TITLE
Disable url_encode on query parameters

### ISSUE THREAD

**Issue by stefansundin** [jnunemaker/httparty#437]
Hello.

I attempted to do this yesterday, but it fails because the `:` is encoded to `%3A` and I can't figure out a way to disable it:
```ruby
HTTParty.get "https://api.github.com/search/code", query: {q: "monkey%20user:stefansundin"}
```

I ended up monkey patching `HTTParty::HashConversions.normalize_param` and removed the call to `ERB::Util.url_encode`.

Today I realized that this call works:
```ruby
HTTParty.get "https://api.github.com/search/code?q=monkey%20user:stefansundin"
```

Basically:
- Working url: https://api.github.com/search/code?q=monkey%20user:stefansundin
- Broken url: https://api.github.com/search/code?q=monkey%20user%3Astefansundin

It would be nice to make the first call work somehow. Thanks!

**Comment by stefansundin** [comment]
Actually, it seems that the issue was caused by me using `%20`, so the url_encode call converted that to `%2520`, which ultimately made the call "fail". My bad.

**Comment by vcavallo** [comment]
I'm having the same issue. A colon in my query params is getting encoded to `%3A`, which the API I'm using doesn't understand. other query params (not using colons or other punctuation) work fine. Any way to skip the encoding without monkey patching?
