### ISSUE TITLE
HTTP Basic Auth when expecting Net Digest Auth leads to Nil

### ISSUE THREAD

**Issue by commel** [jnunemaker/httparty#447]
The Shopware shopsystem uses net digest auth to authentificate remote api calls. So i implemented that. Now the customer has added http basic auth upon that to lock the shop while development.

This lead to this error:
```ruby
blablablacustomerrormessage: undefined method `gsub' for nil:NilClass
/home/xxx/bin/jruby-1.7.22/lib/ruby/gems/shared/gems/httparty-0.13.7/lib/httparty/net_digest_auth.rb:71:in `parse'
/home/xxx/bin/jruby-1.7.22/lib/ruby/gems/shared/gems/httparty-0.13.7/lib/httparty/net_digest_auth.rb:30:in `initialize'
/home/xxx/bin/jruby-1.7.22/lib/ruby/gems/shared/gems/httparty-0.13.7/lib/httparty/net_digest_auth.rb:7:in `digest_auth'
/home/xxx/bin/jruby-1.7.22/lib/ruby/gems/shared/gems/httparty-0.13.7/lib/httparty/request.rb:187:in `setup_digest_auth'
/home/xxx/bin/jruby-1.7.22/lib/ruby/gems/shared/gems/httparty-0.13.7/lib/httparty/request.rb:178:in `setup_raw_request'
/home/xxx/bin/jruby-1.7.22/lib/ruby/gems/shared/gems/httparty-0.13.7/lib/httparty/request.rb:114:in `perform'
/home/xxx/bin/jruby-1.7.22/lib/ruby/gems/shared/gems/httparty-0.13.7/lib/httparty.rb:545:in `perform_request'
/home/xxx/bin/jruby-1.7.22/lib/ruby/gems/shared/gems/httparty-0.13.7/lib/httparty.rb:476:in `get'
```

I fixed it in my fork and will send you a pull request. The fix is simple but I would like to have this in the official release.

**Comment by johannes112** [comment]
@commel How did you manage to get a successful connection to shopware with basic and digest auth via httparty?

**Comment by commel** [comment]
Via pull request #448 which is not in a release yet. Otherwise it is just this option
```ruby
class XYZ
include HTTParty
  digest_auth your_username, your_password
end
```

**Comment by johannes112** [comment]
Thx for the quick answer. 
For the connection to the server I have to use basic auth but for the connection to shopware I have to use digest auth.
I can use only one method of authentication simultaneously. How did you manage it first to use basic and then digest auth?

```
module AuthenticateVariants
  def authenticator()
    class_httparty = self.class
    url = class_httparty.base_uri
    useBasic()
    counter = 0
    begin
    counter = counter+1
    p counter
    response1 = class_httparty.get(url)
    rc1 = response1.code 
    p "RESPONSECODE: #{rc1}"
    url2 = "#{url}/api/orders"
    class_httparty.base_uri url2 
    useDigest()
    response2 = class_httparty.get(url2)
    rc2 = response2.code
    end while rc2!=200 && counter<2
  end
  
  #use for connection with htaccess but it does not work as expected
  def useBasic()
    class_httparty = self.class
    #set url
    class_httparty.default_options.delete(:digest_auth)
    class_httparty.basic_auth @user, @pass
    p class_httparty.basic_auth @user, @pass
  end
  def setBasic (username, password)
    @user = username
    @pass = password
  end
  def getBasic 
    @user
    @pass
  end
  #use for connection with shopware api
  def setDigest (username, password)
    @username = username
    @password = password
  end
  def getDigest 
    @username
    @password
  end
  def useDigest()
    class_httparty = self.class
    #class_httparty.base_uri 
    #set url
    class_httparty.default_options.delete(:basic_auth)
    class_httparty.digest_auth @username, @password
  end
end
```

main.rb:
`
shopware_user1 = ShopwareApi.new()
shopware_user1.setUrl(urlname)
shopware_user1.setDigest(username, apikey)
shopware_user1.setBasic(husername, hapikey)
shopware_user1.authenticator()
`

**Comment by commel** [comment]
The use_digest seems to imply that. I didn't change any code when they introduced basic-auth. I just had to add this fix. 

Do you use the api key as password?

**Comment by johannes112** [comment]
Sorry, it is a bad variablename for my password. 
If i will not delete the default_options (class_httparty.default_options.delete(:basic_auth)) there will appear the authentication error 

> _only one authentication method, :basic_auth or :digest_auth may be used at a time (ArgumentError)_
