### ISSUE TITLE
Exception Object Expected

### ISSUE THREAD

**Issue by jbolles5** [jnunemaker/httparty#453]
Hello all:

I have am attempting to make a call using HTTParty, and for the life of me cannot figure out what I am doing wrong. 

it always throws the following exception on the HTTParty.get line:
```
A TypeError occurred in subjects#suggest_process:
exception object expected
```

Here is what I have:
```
escaped_url = Rack::Utils.escape(params['suggestion']['url'])

call_url = 'http://access.alchemyapi.com/calls/url/URLGetRankedKeywords'

begin
        response = HTTParty.get(call_url, apikey: 'my_api_key', url: escaped_url, outputMode: 'json')
rescue => e
        raise e
end
```

I have also tried:
```
escaped_url = Rack::Utils.escape(params['suggestion']['url'])

params = { apikey: 'my_api_key', url: escaped_url, outputMode: 'json' }

call_url = 'http://access.alchemyapi.com/calls/url/URLGetRankedKeywords'

begin
        response = HTTParty.get(call_url, params)
rescue => e
        raise e
end
```

And last but not least:

```
escaped_url = Rack::Utils.escape(params['suggestion']['url'])

call_url = "http://access.alchemyapi.com/calls/url/URLGetRankedKeywords?apikey=my_api_key&url=#{escaped_url}&outputMode=json"

begin
        response = HTTParty.get(call_url)
rescue => e
        raise e
end
```

The resulting URL works fine when put into a browser, so I know the endpoint is not throwing an error. I have Googled, but am not seeing much. Any direction would be much appreciated.

**Comment by jbolles5** [comment]
For giggles I also tried:

```
escaped_url = Rack::Utils.escape(params['suggestion']['url'])

params = { apikey: 'my_api_key', url: escaped_url, outputMode: 'json' }

call_url = 'http://access.alchemyapi.com/calls/url/URLGetRankedKeywords'

begin
        response = HTTParty.get(call_url, query: params)
rescue => e
        raise e
end
```

But no love ...

**Comment by jnunemaker** [comment]
With a little script we can actually run and reproduce there isn't much we can do to help. Also stuff like this is good for the mailing list. Probably more people that can help there. https://groups.google.com/forum/#!forum/httparty-gem

If you can get a small script to reproduce, we can definitely take a look.
