### ISSUE TITLE
Feature Proposal: Raise on some HTTP status codes

### ISSUE THREAD

**Issue by dccunha** [jnunemaker/httparty#454]
I would like if HTTParty throw an exception on some HTTP status codes. I thought in an option that would turn this feature on and define what status codes would throw exceptions.

Something like this:

```ruby
class Foo
  include HTTParty
  raises_on status_codes: (400..599).to_a
end
```

What do you think of this? Can I send a pull request following this idea?

**Comment by jnunemaker** [comment]
I'd be open to seeing a PR, but I'm not really sure I like this idea. I'd probably rather just see a layer on top at the application level or something that does this if you want it.

**Comment by jnunemaker** [comment]
Closing the issue, but thanks for the proposal and do let me know if you whip something up.
