### ISSUE TITLE
Uninitialized Constant error when included in class

### ISSUE THREAD

**Issue by jgeis** [jnunemaker/httparty#463]
I am getting an error when I do it properly with the latest Ruby and HTTParty by doing:
```ruby
class Fitbit
  include HTTParty
  base_uri 'api.fitbit.com'
...
```

The error was this:
```
uninitialized constant Fitbit::HTTParty (NameError)
```

Could anyone help?

**Comment by jnunemaker** [comment]
Issues are for known bugs more than questions. I would try getting help from one of these sources: https://github.com/jnunemaker/httparty#help-and-docs. 

It seems like maybe you are missing a require of the gem.
