### ISSUE TITLE
Empty array is ignored when passed as a param

### ISSUE THREAD

**Issue by codemang** [jnunemaker/httparty#469]
```
res = HTTParty.get('http://google.com', query: {fake_array: []})
res.request.last_uri.to_s == 'http://www.google.com/'
```
but...
```
res = HTTParty.get('http://google.com', query: {fake_array: [1]})
res.request.last_uri.to_s == 'http://www.google.com/?fake_array%5B%5D=1'
```

Is this intended behavior? Is this a limitation of HTTP?

**Comment by jnunemaker** [comment]
I think it might be [this line](https://github.com/jnunemaker/httparty/blob/2315322422f7de2ac5ef779030113a91f7b62736/lib/httparty/request.rb#L204) that rejects empty params which was [introduced here](https://github.com/jnunemaker/httparty/commit/5db97a709c89e353b31877b8a74e086b0f835d97). We probably just need a new test that empty array's are fine and trailing ampersands don't get added. Totally open to a PR.
