### ISSUE TITLE
Content-Type Does not send when I try to use a new Hash syntax on header

### ISSUE THREAD

**Issue by kidush** [jnunemaker/httparty#472]
### It's work fine

``` ruby
{ 'Content-Type' => 'application/json' }
```
### but  when I try to use this way:

``` ruby
{ 'Content-Type': 'application/json' }
```

the header doesn't send :(

**Comment by jnunemaker** [comment]
> the header doesn't work :(

Does it error? Just not send? Can you provide more details please. There isn't much I can do to help without a small script that shows what you expect and what happened.

**Comment by kidush** [comment]
Sorry, @jnunemaker I've changed the title 😄 

for example: 

```ruby
class Request
  include HTTParty
  # this way does not send the header
  headers 'Content-Type': 'application/json'
  # this way works
  headers 'Content-Type' => 'application/json'
end
```

Other thing that I've seen, in ruby 2.3 the request works fine with `{ 'Content-Type': 'application/json' }` in ruby 2.2 does not work.

In Ruby 2.2 there is a method `capitalize` in Net::HttpHeader specifically at line 172 
that is different from Ruby 2.3.

File: `/net/http/header.rb`
```ruby
# ruby 2.2
def capitalize(name)
  name.split(/-/).map {|s| s.capitalize }.join('-')
end

# ruby 2.3
def capitalize(name)
  name.to_s.split(/-/).map {|s| s.capitalize }.join('-')
end
```

**Comment by jnunemaker** [comment]
I've actually never used `headers 'Content-Type': 'application/json'` syntax. I didn't even know it worked. I thought you always need to do a string with the =>, a symbol with => or keyword with :. Does it work if you do `headers :'Content-Type' => 'application/json'`? Note the ":" before content type forcing it to be a symbol. Probably will. I'm wondering if this is just a ruby hash syntax thing or a net/http thing and if there is anything httparty can or should do. What are your thoughts?

**Comment by kule** [comment]
@jnunemaker this caught me out actually - where I was setting the ````Content-Type: 'application/json'```` but the post request ended up being changed to ````application/x-www-form-urlencoded```` instead.  I put it down to being too used to HashWithIndifferentAccess! :)

The new "string": symbol syntax appeared in ruby 2.2 I believe.

Since no one had replied I thought I'd try out your suggestion - for me it didn't work with ````headers :'Content-Type' => 'application/json'```` either, which is to be expected I guess, if it only works with strings and not symbols.

I guess it'd be nice if httparty it worked with symbols too or at least outputted a warning the debug log?

**Comment by jnunemaker** [comment]
> I guess it'd be nice if httparty it worked with symbols too or at least outputted a warning the debug log?

Ah yeah, forgot this was a string vs symbol thing so doesn't matter how you make the symbol. A warning or something makes sense to me. I guess we could call to_s instead, but that might lead to some weird things sneaking in. Feels better to warn or raise early and let devs fix it.

**Comment by alex-hall** [comment]
Would it make any sense to scope the solution to this problem only? We've had several production problems related to this bug, and just realized it was the string vs symbol issue.

I understand that ruby added new functionality that you did not intend on supporting, but if you write ruby the new way, the HTTP request has a pretty serious side effect. 

I would be in favor of auto-converting the symbol to a string to make new development easier, but honestly don't know what security concerns there would be around solving the problem ONLY [for headers](https://github.com/jnunemaker/httparty/blob/master/lib/httparty.rb#L216)

I'd be glad to write up a pull request for either implementation as this bug has bit us a few time already. 

Pairs: 
@lm185074
@alex-hall

**Comment by dinomite** [comment]
I've run into this, and found it quite confusing.

**Comment by daveroberts** [comment]
Confirmed.  It looks like httparty is including a second Content-Type:

```
POST / HTTP/1.1
Accept: application/json
Content-Type: application/json
Connection: close
Host: localhost:4567
Content-Length: 250
Content-Type: application/x-www-form-urlencoded
```

**Comment by Quintasan** [comment]
It sure does.

Consider the following example

```ruby
require 'httparty'

class GetResponse
  include HTTParty
  base_uri "https://api.getresponse.com/v3"
  headers "Content-Type": "application/json", "X-Auth-Token": "api-key #{Rails.application.secrets.getresponse_api_key}"
  debug_output

  def self.subscribe(email:, campaign_id:)
    payload = { email: email, campaign: { campaignId: campaign_id } }
    response = post("/contacts", body: payload.to_json)
  end
end
```

Output:
```ruby
2.4.1 (main):0 > r = GetResponse.subscribe(email: "redacted", campaign_id: Rails.application.secrets.getresponse_campaign)
opening connection to api.getresponse.com:443...
opened
starting SSL for api.getresponse.com:443...
SSL established
<- "POST /v3/contacts HTTP/1.1\r\nContent-Type: application/json\r\nX-Auth-Token: api-key [redacted]\r\nConnection: close\r\nHost: api.getresponse.com\r\nContent-Length: 66\r\nContent-Type: application/x-www-form-urlencoded\r\n\r\n"
<- "{\"email\":\"[redacted]\",\"campaign\":{\"campaignId\":\"[redacted]\"}}"
-> "HTTP/1.1 400 Bad Request\r\n"
-> "Server: nginx\r\n"
-> "Date: Thu, 24 Aug 2017 11:48:07 GMT\r\n"
-> "Content-Type: application/json;charset=utf-8\r\n"
-> "Transfer-Encoding: chunked\r\n"
-> "Connection: close\r\n"
-> "\r\n"
-> "31c\r\n"
reading 796 bytes...
-> "{\n    \"httpStatus\": 400,\n    \"code\": 1000,\n    \"codeDescription\":\"General error of validation process, more details should be in context section\",\n    \"message\": \"Validation error, see context section for more information\",\n    \"moreInfo\": \"https://apidocs.getresponse.com/en/v3/errors/1000\",\n    \"context\": [\n        {\n            \"validationType\": \"body\",\n           \"fieldName\": \"email\",\n            \"originalValue\": \"\",\n         \"errorDescription\": \"Required field empty\"\n        },\n        {\n            \"validationType\": \"body\",\n            \"fieldName\": [\n           \"campaign\",\n                \"campaignId\"\n            ],\n       \"originalValue\": \"\",\n            \"errorDescription\": \"Required field empty\"\n        }\n    ],\n    \"uuid\": \"539b7dc1-309c-426c-a32b-2f95f34ccb87\"\n}"
read 796 bytes
reading 2 bytes...
-> "\r\n"
read 2 bytes
-> "0\r\n"
-> "\r\n"
Conn close
```

**Comment by mtn** [comment]
@Quintasan I'm dealing with the same `Content-Type` problem. Did you come to any solution?

**Comment by Quintasan** [comment]
@mtn Yeah, you just have to use the old Hash syntax. For example:

```ruby
headers "Content-Type" => "application/json"
```

**Comment by lostapathy** [comment]
FWIW, I just spent quite a bit of time wrestling with problems that boiled down to this issue.  This seems like something more and more likely to cause issues as more people use the "new ruby syntax" to define hashes.
