### ISSUE TITLE
Wrong redirect url if location header is duplicated

### ISSUE THREAD

**Issue by DarthMax** [jnunemaker/httparty#478]
There seems to be a bug in several Nginx versions which duplicates the location header in 301 responses. 

https://github.com/pagespeed/ngx_pagespeed/issues/725

This bug causes a wrong redirect url to be extracted which results in a _URI::InvalidURIError_

Example:
```ruby
HTTParty.head "http://www.neuepresse.de/Hannover/Meine-Stadt/Gegen-TTIP-Die-grosse-Demo-in-Hannover" 
#URI::InvalidURIError: bad URI(is not URI?): http://www.neuepresse.de/Hannover/Obama-in-Hannover/Gegen-TTIP-Die-grosse-Demo-in-Hannover, http://www.neuepresse.de/Hannover/Obama-in-Hannover/Gegen-TTIP-Die-grosse-Demo-in-Hannover
```

and the response header:

```shell
$ curl -I 'http://www.neuepresse.de/Hannover/Meine-Stadt/Gegen-TTIP-Die-grosse-Demo-in-Hannover'

HTTP/1.1 301 Moved Permanently
Server: Apache
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Last-Modified: Wed, 08 Jun 2016 11:29:01 GMT
Pragma: no-cache
X-Powered-By: eZ Publish Platform
Served-by: www.neuepresse.de
Content-Language: de-DE
Status: 301 Moved Permanently
Location: http://www.neuepresse.de/Hannover/Obama-in-Hannover/Gegen-TTIP-Die-grosse-Demo-in-Hannover
Location: http://www.neuepresse.de/Hannover/Obama-in-Hannover/Gegen-TTIP-Die-grosse-Demo-in-Hannover
X-UA-Compatible: IE=edge
X-EZ-WEB: mol13n002
Cache-Control: no-cache, 
Cache-Control: no-cache
Content-Type: text/html; charset=UTF-8
X-EZ-HAP: mol13n004
Date: Wed, 08 Jun 2016 11:29:01 GMT
Connection: keep-alive
Set-Cookie: eZSESSIDcf3fc916339b02ad9c14aca2425ccf53=7ihbf3ljtkbpjurlm9luckfak0; path=/
Set-Cookie: VAR=dUhHOAQNVt9L8wiu/YWN9D8J2C+2rvGd; path=/; domain=www.neuepresse.de
Set-Cookie: DCID=f3; path=/; domain=www.neuepresse.de
```

This is of course no standard conform response header, but I was wondering if there would be away to avoid these errors conveniently as they seem to be quite frequent at the moment?

**Comment by jnunemaker** [comment]
I'd prefer to stick to the standards. Is passing the Location header more than once standard in the http spec? It seems very odd.

**Comment by DarthMax** [comment]
Nope this is allowed according to http specs as stated in [1] and [2].
The problem is that there seem to be quite a lot websites with this kind of problem, which is quite annoying. 

Most browsers seem to deal with it in a way that they redirect normally if both locations are the same, otherwise they throw a network error. At least it would be nice to have a distinct error for that so that one could handle the situation, but the current behavior of simply joining both locations and throwing an `InvalidURI` on the the redirect request is hard to handle. 

[1] https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
[2] https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.30

**Comment by jnunemaker** [comment]
> At least it would be nice to have a distinct error for that so that one could handle the situation

That works for me. I'd definitely be open to an error to raise when two locations are returned and follow redirects is enabled.
