### ISSUE TITLE
Example does not seem to work

### ISSUE THREAD

**Issue by georgeu2000** [jnunemaker/httparty#479]
From [headers_and_user_agents example](https://github.com/jnunemaker/httparty/blob/master/examples/headers_and_user_agents.rb):

    response = HTTParty.get('http://example.com', headers: {"User-Agent" => APPLICATION_NAME})

raises 

> /Users/george/.rbenv/versions/2.3.1/lib/ruby/2.3.0/net/http/header.rb:18:in `block in initialize_http_header'

However works without `header` key:

    HTTParty.get('http://example.com', {"User-Agent" => APPLICATION_NAME})

Has the API been updated?

**Comment by georgeu2000** [comment]
Never mind. I found the problem. The headers were:

    { 'Authorization' =>  ENV[ 'TOP_SECRET_AUTH' ]}

ENV was not set so the value was `nil`.

Which raised

>    Error processing request: NoMethodError: undefined method `strip' for nil:NilClass

**Comment by jnunemaker** [comment]
🎉

**Comment by cjjuice** [comment]
🎉  forgot to set an ENV var in an app and this helped me. I was like 'Where am I calling 'strip'!' lol

**Comment by jrob00** [comment]
Thanks for writing this up! Coming across this helped me solve a similar issue in a legacy app.

**Comment by georgeu2000** [comment]
Sure, no problem. Many people run into the same issue...
