### ISSUE TITLE
Can we get a release bump?

### ISSUE THREAD

**Issue by vancluever** [jnunemaker/httparty#480]
There's at least one very valuable feature in the latest source (the `raise_on` and exception handling bits) that has been added since 0.13.7 - I'm surprised a new gem hasn't been cut in so long!

**Comment by md5** [comment]
I'd also like to get a release with 37dfb42382e4365fb79d0323cd531198121cfb81.

**Comment by Eric-Guo** [comment]
Same, but I'm concern the [json depencency](https://github.com/jnunemaker/httparty/pull/464)...

**Comment by jnunemaker** [comment]
0.14.0 is out.
