### ISSUE TITLE
HTTParty does not support arbitrary HTTP Methods

### ISSUE THREAD

**Issue by duane** [jnunemaker/httparty#484]
HTTParty explicitly checks the HTTP method against `SupportedHTTPMethods`. As far as I can see, there is a) no provided rationale—this is typically decided by the 405 response, not the client—and b) no way to override.

This means alternative http methods (such as a `PURGE` method to purge a cache key from a local cache) cannot be executed at all with this library because the method isn't valid.

Is there any available workaround?

**Comment by jnunemaker** [comment]
I believe the reason it was added was because an accompanying method is required:
https://github.com/jnunemaker/httparty/blob/0d808c7f3a68b8d091506e22003fc00dd84bf6a6/lib/httparty.rb#L485-L487

Adding a purge method should make it work. I'm open to a PR to add purge or to improve how that works.
