### ISSUE TITLE
Does'n work on ruby 1.9.3

### ISSUE THREAD

**Issue by fanantoxa** [jnunemaker/httparty#486]
A new version of JSON gem doesn't support ruby 1.9.3 more. 
```Gem::InstallError: json requires Ruby version ~> 2.0.```
Now we have to fix it or stop supporting ruby 1.9.3

@jnunemaker What you think about it?

**Comment by jnunemaker** [comment]
Can we just tweak the gemspec requirements? Thoughts on that?

**Comment by fanantoxa** [comment]
@jnunemaker Also gem `ruby_dep` don't support ruby 1.9.0 (min 2.0.0).
I've tried to resolve this dependency issues with:

```
gem 'json',     '= 1.8.3',    platforms: [:ruby_19]
gem 'listen',   '= 3.0.8',    platforms: [:ruby_19]
```

It's should work but it's a dirty hack to make it work.
But I'm not sure that it's a good idea.
Ruby 1.9.3 not longer supporting and many of gem stopped supporting it too.
I think will be better to stop support it for HTTParty too.

**Comment by jnunemaker** [comment]
We can stop supporting 1.9. I'm cool with that.

**Comment by jnunemaker** [comment]
@fanantoxa would you mind whipping a PR together since you seem to have the context right now? If not let me know.

**Comment by fanantoxa** [comment]
@jnunemaker sure. I saw that you've already updated gem for drop 1.9.3 version and merged my PR.
So I think we can close this issue
