### ISSUE TITLE
0.14 breaks some code

### ISSUE THREAD

**Issue by zedalaye** [jnunemaker/httparty#489]
I have this code (from the licencetobill gem) that is broken when I upgrade to HTTParty 0.14 :

```ruby
module LicenceToBill
  class Manager
    def self.return_collection(klass, params)
      return [] if params.nil?
      if params.kind_of?(Array)
        params.map { |hash| klass.new(hash) }
      else
        status = params.parsed_response['Status']
        return [] if status === 404
        hash = JSON.parse(params.body)
        return [ LicenceToBill::Error.new(hash) ] if status
        [klass.new(hash)]
      end
    end
  end
end
````

[Link](https://github.com/zedalaye/licencetobill/blob/master/lib/licencetobill/manager.rb#L8) to the code

Ruby throws an error on status = params.parsed_response['Status']. Is there a new way to write this code with HTTParty 0.14 ?

**Comment by zedalaye** [comment]
A precision, this is how looks the server response when the requested resources does not exists : 

````
params.parsed_response == {"Status"=>404, "Message"=>"Not found"}
````

That's why I used to check the value of  ````params.parsed_response['Status']````

**Comment by jnunemaker** [comment]
What is the error that it is throwing and the backtrace of that error? Also, what are `klass` and `params` that get passed to the return_collection method above?

**Comment by zedalaye** [comment]
Got it. The fact is that the server returns a JSON array. In 0.13.x, `params.kind_of?(Array)` is `true`, in 0.14.0, the "same" `params.kind_of?(Array)` is `false`.

**Comment by zedalaye** [comment]
To workaround the problem and make the LicenceToBill gem work with HTTParty 0.14, I just changed the above method to :

````ruby
module LicenceToBill
  class Manager
    def self.return_collection(klass, params)
      return [] if params.nil?
      if params.parsed_response.is_a?(Array)
        params.map { |hash| klass.new(hash) }
      else
        status = params.parsed_response['Status']
        return [] if status === 404
        hash = JSON.parse(params.body)
        return [ LicenceToBill::Error.new(hash) ] if status
        [klass.new(hash)]
      end
    end
  end
end
````
replacing ` if params.kind_of?(Array)` by ` if params.parsed_response.is_a?(Array)`

Not sure but in `HTTParty::Response`, shouldn't `class` method be defined as :

```ruby
def class
  parsed_response.class
end
````
instead of simply returning "Response" which is a BasicObject. I tested this solution and it "seems" to work (in my case), I didn't run the specs.

**Comment by zedalaye** [comment]
It seems this was the expected behaviour before 0.14, as every missing method call was delegated to parsed_response, is_a? / kind_of? were working as I expected. 

Due to https://github.com/jnunemaker/httparty/commit/c4a031d70d09a5d1dff7661ad71030bddbcf6e71, is_a? / kind_of will now only compare against HTTParty::Response. 

You will not change that, won't you ? :)

**Comment by jnunemaker** [comment]
Ah, gotcha. Yeah I think the current behavior is correct and the previous was wrong.
