### ISSUE TITLE
Redirection breaks when location header is a network-path reference

### ISSUE THREAD

**Issue by capicue** [jnunemaker/httparty#491]
Whenever the location header in a redirect is a network-path reference (something like "//www.example.com"), a RedirectionTooDeep error occurs. The reason for this is "//www.example.com" is considered a [relative URI](https://tools.ietf.org/html/rfc3986#section-4.2). This causes [`HTTParty::Request#uri`](https://github.com/jnunemaker/httparty/blob/6049c5e798277de0775b286553a2802ec87bd883/lib/httparty/request.rb#L79) to append it to the end of the existing URI. This results in a series of redirects as follows:

http://example.com
http://example.com//www.example.com
http://example.com//www.example.com//www.example.com
etc.
(the location header for all of these is "//www.example.com")

For an in-the-wild example, I encountered this with `HTTParty.get("http://zillow.com")`

**Comment by jnunemaker** [comment]
Thanks for the in-the-wild example!
