### ISSUE TITLE
BOM characters \xEF\xBB\xBF

### ISSUE THREAD

**Issue by josegrad** [jnunemaker/httparty#498]
When the response body contains BOM characters the Json parsing fails.
This response breaks it:

"\xEF\xBB\xBF[{\"id...

I get:

Exception Encoding::UndefinedConversionError
Error "\xEF" from ASCII-8BIT to UTF-8

I'm using httparty 0.14.0
Ruby 2.2.4

Any hints?

I can make the request with other libraries and clean up the BOM, but httparty is a dependency of other gem I use.

**Comment by Rsullivan00** [comment]
We ran into the same issue and ended up manually stripping the BOM and manually calling `JSON.parse` on the cleaned result.
