### ISSUE TITLE
How to symbolize JSON keys or suppress parsing?

### ISSUE THREAD

**Issue by georgeu2000** [jnunemaker/httparty#500]
I would like JSON response keys to be symbols, but did not see a way of doing that.

Alternately, how to suppress parsing JSON?

    HTTParty.get 'http://example.com'
    => { "foo" => "bar" }

**Comment by jnunemaker** [comment]
> I would like JSON response keys to be symbols, but did not see a way of doing that.

There is no automatic way to do key conversion to symbols and I don't plan on adding it. Newer versions of ruby have symbol gc, but older ones don't which would make your application open to attack simply by an external service returning lots of different keys, which would increase memory usage.

If you are using from Rails or have access to ActiveSupport, you can use `symbolize_keys` to convert keys.

> Alternately, how to suppress parsing JSON?

The format is inferred from the content type header in the response. You can see a mapping of supported formats [here](https://github.com/jnunemaker/httparty/blob/247d541f93e27d96e8226ec222a0c488886d1017/lib/httparty/parser.rb#L40-L52). If you want to override that, you can do so by passing format as plain:

```ruby
HTTParty.get 'http://example.com', format: :plain
```

**Comment by georgeu2000** [comment]
OK, thanks. Overriding with `format: :plain` is great. 

I don't see anything in the docs about automatic parsing or overriding. Would you be open to a PR?

**Comment by jnunemaker** [comment]
Always open to new docs if they make sense and will help!
