### ISSUE TITLE
403 forbidden error on http request

### ISSUE THREAD

**Issue by AyanamiPT** [jnunemaker/httparty#504]
Hi, I'm trying to perform an HTTP request to my Mirth Server API through a Rails application, but it always returns Net::HTTPServerException (403 "Forbidden"). I can't understand what is the problem. If I use the same URL and set Content-Type: application/xml in Google's Advanced Rest Client, it works, but from my rails app it returns the above error. The same problems happens if I try to perform a post to authenticate a user in the Mirth API (see code below).

This is the code in my controller:

```
@login = HTTParty.post("https://#{server}:#{port}/api/users/_login",
                         {:body => [{"username" => "xxxxxxxx", "password" => "xxxxxxxxxxx"}],                              
                          :headers => { 'Content-Type' => 'application/x-www-form-urlencoded',
                                        'Accept' => 'application/xml'}
                         })
```

```
@response = HTTParty.get("https://#{server}:#{port}/api/server/configurationMap",
                           {:basic_auth => {:username => "xxxxxxxx", :password => "xxxxxxxxxxx"},
                            :headers => { 'Content-Type' => 'application/xml'}
                          })
```

If I try to make the request via git bash using `curl -X GET --header 'Accept: application/xml' 'https://192.168.4.196:8444/api/server/configurationMap'`, it gives "curl: (56) received http code 403 from proxy after connect".

What can be wrong?
Thank you in advance!

**Comment by jnunemaker** [comment]
I'm not familiar with "Mirth Server API". What is that? Something you built or that exists online? 

I don't believe this is a bug with httparty, sounds more like a question, so I'm going to close the issue, but feel free to respond and I'll try to help if I can when I have time.
