### ISSUE TITLE
Ruby 2.3.3 and HTTParty

### ISSUE THREAD

**Issue by resistorsoftware** [jnunemaker/httparty#505]
Using RVM to load and run with Ruby 2.3.3

* did a gem install httparty
* gem list command shows: httparty (0.14.0)
* run a pry session
* require 'httparty'
    
     pry
     [1] pry(main)> require 'httparty'
     LoadError: cannot load such file -- httparty
     from (pry):1:in `require'

**Comment by jnunemaker** [comment]
Did you require rubygems?

**Comment by jnunemaker** [comment]
I'm closing as this isn't an httparty issue, but I'm happy to try to help if I can still.
