### ISSUE TITLE
HTTParty permanently overrides default request headers of Net::HTTP

### ISSUE THREAD

**Issue by qsona** [jnunemaker/httparty#506]
## Version
httparty 0.13.7
(Ruby on Rails 4.2.6)

## Reproduce Steps

1) `HTTParty.get('http://httpstat.us/204', debug_output: $stdout)`
request log:
`<- "GET /204 HTTP/1.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nAccept: */*\r\nUser-Agent: Ruby\r\nConnection: close\r\nHost: httpstat.us\r\n\r\n"`

2) `HTTParty.get('http://httpstat.us/204', headers: {}, debug_output: $stdout)`
request log:
`<- "GET /204 HTTP/1.1\r\nConnection: close\r\nHost: httpstat.us\r\n\r\n"`

3) `HTTParty.get('http://httpstat.us/204', debug_output: $stdout)`
request log:
`<- "GET /204 HTTP/1.1\r\nConnection: close\r\nHost: httpstat.us\r\n\r\n"`

On the second request, I specified `headers: {}` option, then the default headers (Accept-Encoding, Accept, User-Agent) are removed. And after that, even if I don't specified headers option, these headers don't come back.

**Comment by jnunemaker** [comment]
Closed by https://github.com/jnunemaker/httparty/pull/518
