### ISSUE TITLE
HTTParty failing to retrieve certificates 

### ISSUE THREAD

**Issue by builders-inc** [jnunemaker/httparty#509]
I'm attempting to use HTTParty.get ('website') to request a page but when I use https://website I get a ssl_connect certificate verify failed error

"SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)"

My plan is to convert the page to a nokogiri object where I can collect some data from it.  If I use the insecure site "http://webiste" the code works but httparty doesn't pass html, it passes something else completely.

I'm running Ruby 2.2.6 and pulled httparty in from the command prompt via gem install httparty.

I'm new to Ruby so any help would be greatly appreciated

**Comment by jnunemaker** [comment]
Could you provide an example failing script that I could use to repeat until I get the result to succeed? Without this, it is difficult for me to help. Closing due to lack of enough information to help, but if you can get me more info I would be happy to try.
