### ISSUE TITLE
Please allow upgrade of gem "json"

### ISSUE THREAD

**Issue by david-a-wheeler** [jnunemaker/httparty#517]
httparty (0.13.7) requires json (~> 1.8), but json is now at version 2.0.3.

Please allow users of httparty to upgrade to the current version of the json gem.

**Comment by CJStadler** [comment]
@david-a-wheeler I believe this has been fixed in [0.14.0](https://rubygems.org/gems/httparty/versions/0.14.0)

**Comment by jnunemaker** [comment]
Yep! Fixed by https://github.com/jnunemaker/httparty/commit/37dfb42382e4365fb79d0323cd531198121cfb81. If you upgrade to 0.14 you will be good to go.
