### ISSUE TITLE
Request to support Ruby 2.4.0

### ISSUE THREAD

**Issue by Lucashuang0802** [jnunemaker/httparty#524]
It failed due to the json error: https://github.com/jnunemaker/httparty/pull/523

**Comment by Lucashuang0802** [comment]
@jnunemaker

**Comment by Lucashuang0802** [comment]
Possible duplicate with #510

**Comment by jnunemaker** [comment]
Yep, looks like a dup of #510. Agreed that I'd like to fix whatever problems there are currently.
