### ISSUE TITLE
How to download file with httparty?

### ISSUE THREAD

**Issue by lidashuang** [jnunemaker/httparty#525]
I want download mp4 file with httparty 

code:

      filename = "tmp/#{cdn.id}.mp4"
      File.open(filename, "w") do |file|
        HTTParty.get(cdn.original_cdn_url, stream_body: true) do |fragment|
          file.write(fragment)
        end
      end

The `cdn.original_cdn_url` is  
https://scontent.cdninstagram.com/t50.2886-16/18344103_1517115991634527_48235403311841280_n.mp4

but some error

```
Encoding::UndefinedConversionError: "\xC3" from ASCII-8BIT to UTF-8
```

**Comment by lidashuang** [comment]
```
 def upload_oss
    cdn_infos.each do |cdn|
      next if cdn.new_cdn_url
      filename = "tmp/#{cdn.id}.mp4"
      File.open(filename, "w") do |file|
        file.binmode
        HTTParty.get(cdn.original_cdn_url, stream_body: true) do |fragment|
          file.write(fragment)
        end
      end
    end
  end
```
with binmode
`file.binmode`

**Comment by saurabhnanda** [comment]
For anyone landing up on this in the future, the code given above might produce incorrect results. In my case, I was trying to download a ZIP file and the following text was added to the beginning of every zip file:

> This resource has been moved temporarily to (some url)

**Comment by paulmakepeace** [comment]
You can add `follow_redirects: true` to `HTTParty.get`

**Comment by alexventuraio** [comment]
How to translate this `curl` request that creates an `example.png` image correctly, to bo done with `HTTParty`?
```sh
# staticmap_example.json
{
  "center": {
    "lat": 47.579,
    "lon": -122.31
  },
  "width": 400,
  "height": 600,
  "zoom": 13
}


curl --request POST \
     --data-binary "@staticmap_example.json" \
     https://stripe-bikemap.appspot.com/map.png \
     --output example.png
```

**Comment by alexventuraio** [comment]
How to translate this `curl` request that creates an `example.png` image correctly, to bo done with `HTTParty`?
```sh
# staticmap_example.json
{
  "center": {
    "lat": 47.579,
    "lon": -122.31
  },
  "width": 400,
  "height": 600,
  "zoom": 13
}


curl --request POST \
     --data-binary "@staticmap_example.json" \
     https://bikemap.appspot.com/map.png \
     --output example.png
```

**Comment by griffero** [comment]
I made a ruby script that just worked:

You need the json file though

```
require 'httparty'
require 'json'
file = File.read('./emojis.json')
data_hash = JSON.parse(file)

data_hash['emoji'].each do |emoji|
  url = emoji['url']
  extension = url.split('.').last
  filename = "output/#{emoji['name']}.#{extension}"
  File.open(filename, "w") do |file|
    file.binmode
    HTTParty.get(url, stream_body: true) do |fragment|
      file.write(fragment)
    end
  end
end
```

**Comment by fadhlimaulidri** [comment]
do you mean like below @paulmakepeace ?
`@response = HTTParty.get(url, body: body, headers: headers, follow_redirects: true, timeout: timeout)`

@defp where we get the file path which have we downloaded?

**Comment by paulmakepeace** [comment]
> do you mean like below @paulmakepeace ?
> 
> `@response = HTTParty.get(url, body: body, headers: headers, follow_redirects: true, timeout: timeout)`

Yes, exactly

**Comment by fadhlimaulidri** [comment]
@paulmakepeace i get error like below. and at the log i find binary of file. how to handle it?

```
"\xCF" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
/Users/mekari/.rvm/gems/ruby-2.7.6/gems/builder-3.2.4/lib/builder/xmlmarkup.rb:287:in `write'
/Users/mekari/.rvm/gems/ruby-2.7.6/gems/builder-3.2.4/lib/builder/xmlmarkup.rb:287:in `<<'
/Users/mekari/.rvm/gems/ruby-2.7.6/gems/builder-3.2.4/lib/builder/xmlmarkup.rb:287:in `_text'
/Users/mekari/.rvm/gems/ruby-2.7.6/gems/builder-3.2.4/lib/builder/xmlbase.rb:119:in `<<'
/Users/mekari/.rvm/gems/ruby-2.7.6/gems/cucumber-3.1.2/lib/cucumber/formatter/html.rb:369:in `block (2 levels) in print_messages'
/Users/mekari/.rvm/gems/ruby-2.7.6/gems/builder-3.2.4/lib/builder/xmlbase.rb:176:in `_nested_structures'
/Users/mekari/.rvm/gems/ruby-2.7.6/gems/builder-3.2.4/lib/builder/xmlbase.rb:69:in `tag!'
```

**Comment by Earlopain** [comment]
The upvoted anwser is not correct anymore, `follow_redirect: true` is the default and doesn't change anything. [This example](https://github.com/jnunemaker/httparty/blob/67cbfbd7c6eb31a212a72d16d20680f131d8de42/examples/stream_download.rb) from the repo shows how to correctly download files when encountering a redirect.

```rb
outfile = Tempfile.new(binmode: true)
HTTParty.get(url) do |fragment|
  next if [301, 302].include?(fragment.code)
  outfile.write(fragment)
end
```
