### ISSUE TITLE
Create a new release :-)

### ISSUE THREAD

**Issue by pratik60** [jnunemaker/httparty#526]
Its been a while since the last release which was on July 25, 2016: https://rubygems.org/gems/httparty

We noticed some flaky specs, which have been fixed in the latest master, courtesy of #518 but not been released to a stable version. Further investigation showed we haven't released for nearly 10 months. Would be great to get a stable release :-)

**Comment by jnunemaker** [comment]
Released 0.15

**Comment by eugeneius** [comment]
Thank you @jnunemaker! 🎉

**Comment by pratik60** [comment]
We just shipped the new version to production. Thanks muchly!

![mqd0iicu4ibvk](https://cloud.githubusercontent.com/assets/2249430/26000360/81d805ec-3720-11e7-954c-3105d290f39e.gif)
