### ISSUE TITLE
HEAD requests are broken since 0.15.0 (undefined method force_encoding for nil:NilClass)

### ISSUE THREAD

**Issue by peret** [jnunemaker/httparty#534]
In versions >= 0.15.0 when I do something like `HTTParty.head("https://www.google.com")`, it fails with this Callstack:
```
NoMethodError: undefined method `force_encoding' for nil:NilClass
	from /Users/peter/.rvm/gems/ruby-2.3.3@ptcshell/gems/httparty-0.15.0/lib/httparty/request.rb:280:in `encode_with_ruby_encoding'
	from /Users/peter/.rvm/gems/ruby-2.3.3@ptcshell/gems/httparty-0.15.0/lib/httparty/request.rb:316:in `_encode_body'
	from /Users/peter/.rvm/gems/ruby-2.3.3@ptcshell/gems/httparty-0.15.0/lib/httparty/request.rb:322:in `encode_body'
	from /Users/peter/.rvm/gems/ruby-2.3.3@ptcshell/gems/httparty-0.15.0/lib/httparty/request.rb:350:in `handle_response'
	from /Users/peter/.rvm/gems/ruby-2.3.3@ptcshell/gems/httparty-0.15.0/lib/httparty/request.rb:158:in `perform'
	from /Users/peter/.rvm/gems/ruby-2.3.3@ptcshell/gems/httparty-0.15.0/lib/httparty/request.rb:347:in `handle_response'
	from /Users/peter/.rvm/gems/ruby-2.3.3@ptcshell/gems/httparty-0.15.0/lib/httparty/request.rb:158:in `perform'
	from /Users/peter/.rvm/gems/ruby-2.3.3@ptcshell/gems/httparty-0.15.0/lib/httparty.rb:563:in `perform_request'
	from /Users/peter/.rvm/gems/ruby-2.3.3@ptcshell/gems/httparty-0.15.0/lib/httparty.rb:536:in `head'
	from /Users/peter/.rvm/gems/ruby-2.3.3@ptcshell/gems/httparty-0.15.0/lib/httparty.rb:629:in `head'
```

It works as expected in version 0.14.0. I'm fairly certain that it is caused by one of the changes in this PR: #513 
Specifically number 6 in that list. When I understand correctly, the body that gets passed to `#encode_with_ruby_encoding` should be nil for most HEAD requests. In earlier versions, the NoMethodError was rescued and the unmodified body (i.e. nil) returned. So this is the commit that broke it: c46663d73ff96d86b92d36208a021bbe58672e7c

I'll provide a PR for this very soon.

**Comment by peret** [comment]
I'm sorry, I just now realized that there already is a PR for that: #530 (but apparently no corresponding issue). Feel free to merge either.

**Comment by jnunemaker** [comment]
Closed by https://github.com/jnunemaker/httparty/pull/530

**Comment by jnunemaker** [comment]
@peret no problem! Thanks for issue, pr and prompt!
