### ISSUE TITLE
warning: assigned but unused variable - encoding

### ISSUE THREAD

**Issue by onetwopunch** [jnunemaker/httparty#552]
I get the warning:
```
warning: assigned but unused variable - encoding
```

on v0.15.6 with Ruby 2.4.1 from the commit https://github.com/jnunemaker/httparty/commit/8c2230cc954bcab9388b44c755811ad5a6c35a21

```
def encode_with_ruby_encoding(body, charset)
  encoding = Encoding.find(charset)
  body.force_encoding(charset)
rescue ArgumentError
  body
end
```
It does appear that the variable encoding is not being used anywhere. I would make a PR, but am unsure of the original intent here or if there's some ruby magic that I'm not seeing.

**Comment by jnunemaker** [comment]
I believe the author's original intention was purely to perform an encoding find which will raise the argument error. You can definitely do a PR to remove the assignment and I will happily merge. Thanks for caring and noticing!

**Comment by onetwopunch** [comment]
Of course. Here ya go: https://github.com/jnunemaker/httparty/pull/557

I didn't remove the assignment but just converted to a string. I'm not a fan of the convention of just putting calls that raise exceptions without `!` that don't have an assignment. Just an aesthetic choice, but no difference in performance.
