### ISSUE TITLE
Reading no_proxy from env

### ISSUE THREAD

**Issue by rakrup** [jnunemaker/httparty#554]
My environment has proxy as well as no_proxy specified in it.
The proxy is read correctly but the no_proxy is not read leading to the local requests being forwarded to the proxy and hence failing.

Does httparty currently read no_proxy from env or can it be specified by some alternate means as well ?

**Comment by jnunemaker** [comment]
I'm assuming that this is something that net/http which httparty uses does for you automatically? I don't think there is anything specifically in httparty for reading from `ENV`, but please let me know if I'm misunderstanding or wrong. Closing the issue to keep things tidy but feel free to continue to correspond.
