### ISSUE TITLE
digest_auth might not work correctly?

### ISSUE THREAD

**Issue by krtschmr** [jnunemaker/httparty#556]
` curl -u username:password --digest -X POST http://$IP:$PORT/json_rpc     -d '{"jsonrpc":"2.0","id":"0","method":"'$METHOD'","params":'"$PARAMS"'}'     -H 'Content-Type: application/json' `

this command works perfect. 
when i try (i think) the same request via httparty it fails with a 401

    include HTTParty
    base_uri "192.168.1.226:18081"
    digest_auth("username", "password")
    options = { body: {"jsonrpc":"2.0","id":"0","method": method, "params": {} }.to_json, auth: {:username=>"username", :password=>"password"}, headers: {"Content-Type": "application/json"}}
    self.class.post('/json_rpc', options)
  `

ain't these request identical?

`digest_auth: {:username=>"username", :password=>"password"}` inside the option hash won't make any difference

**Comment by krtschmr** [comment]
i wrote this whole thing now in a working way


    method="getbalance"
     data = '{"jsonrpc":"2.0","id":"0","method": "'+method+'", "params": {} }'
     args = " -s"
     args << " -u #{username}:#{password} --digest"
     args << " -X POST http://#{host}:#{port}/json_rpc"
     args << " -d '#{data}'"
     args << " -H 'Content-Type: application/json'"
     json = JSON.parse(`curl #{args}`)

would be great if somebody could help me, to get this into HTTParty

**Comment by jnunemaker** [comment]
I don't think you need the `auth` key in the options. Can you try again with that removed? The digest_auth call on the previous line should be all you need.
