### ISSUE TITLE
Add support Socks5 proxy

### ISSUE THREAD

**Issue by MelnikVasya** [jnunemaker/httparty#559]
Add support Net::HTTP.SOCKSProxy.

**Comment by jnunemaker** [comment]
Does ruby support socks5 natively with net/http? I'm willing to add if so, but based on a bit of googling it seems to [require an external dependency](https://stackoverflow.com/a/13882749) (socksify), which I'm not interested in adding to httparty. I'm closing this to keep things tidy, but please let me know if I'm wrong or this ever changes in the future.

**Comment by gresbtim** [comment]
should have been merged
