### ISSUE TITLE
Async HTTP Requests in HTTParty ?

### ISSUE THREAD

**Issue by debashisdeb** [jnunemaker/httparty#560]
Is there any async HTTP Request related methods available in HTTParty ? I searched a lot but couldn't find one. As per my understanding, I think HTTParty makes blocking request calls.

**Comment by jnunemaker** [comment]
There is nothing async built into httparty. Your understanding is correct. It uses net/http under the hood, so however you would use net/http in an async fashion is what I would recommend.
