### ISSUE TITLE
SSL certificate error

### ISSUE THREAD

**Issue by thirumal1** [jnunemaker/httparty#561]
Hi,
I am trying to invoke a API from  CareerOneStop website using httparty, and I getting the following error
"SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed"

**Here is my code snippet**
response = HTTParty.get("https://api.careeronestop.org/v1/apprenticeshipfinder/{user_id}/nurse/Austin%2C%20TX/25/0/0/0/0/0/10",  headers: {"Authorization" => "API Tokenx=="})

-------------------------------------------------------------------------------------------------------

**Here Java example provide by the site**

import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import org.apache.http.HttpEntity;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.utils.URIBuilder;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.util.EntityUtils;

public class CareerOneStopAPISample {
    public static void main(String[] args) throws IOException, URISyntaxException {
	URI uri = new URIBuilder()
		.setScheme("https")
		.setHost("api.careeronestop.org")
		.setPath("/v1/apprenticeshipfinder/{userId}/{keyword}/{location}/{radius}/{apprenticeshipName}/{apprenticeshipSponsor}/{sortColumns}/{sortDirections}/{startRecord}/{limitRecord}")
		.build();
	CloseableHttpResponse response = null;
	HttpGet httpGet = null;
	try {
		CloseableHttpClient httpClient = HttpClients.createDefault();
		httpGet = new HttpGet(uri);
		httpGet.setHeader("Content-Type","application/json");
		httpGet.setHeader("Authorization", "Bearer API Token");
		response = httpClient.execute(httpGet);
		HttpEntity entity = response.getEntity();
		System.out.println(EntityUtils.toString(entity));
	} finally {
		if(httpGet != null) httpGet.releaseConnection();
		if(response != null) response.close();
	}
   }
}

Please advise what am I doing wrong in my code.

Thanks in advance

Rao

**Comment by jnunemaker** [comment]
I think HTTParty tries to verify ssl certs by default: https://github.com/jnunemaker/httparty/blob/d7d81999f70cf8dc6b84373c334cc2ff2ec18991/lib/httparty/connection_adapter.rb#L70-L73. Not ideal, but if you pass `verify: false` the error would go away. Better would be to provide ssl file or path: https://github.com/jnunemaker/httparty/blob/d7d81999f70cf8dc6b84373c334cc2ff2ec18991/lib/httparty.rb#L396-L424.

You can see most of the options here: https://github.com/jnunemaker/httparty/blob/d7d81999f70cf8dc6b84373c334cc2ff2ec18991/lib/httparty/connection_adapter.rb#L164-L210.
