### ISSUE TITLE
A Net::HTTPBadResponse occurred in  user#index

### ISSUE THREAD

**Issue by kunkaiHuang** [jnunemaker/httparty#566]
hello,friends. I use httparty, the post method.Today i have a log like that
```
wrong status line: "-ERR unknown command 'POST'"
/home/git/ruby2.1.2/lib/ruby/2.1.0/net/http/response.rb:41:in `read_status_line'
```
i do not actually know which error! Thank you very much!

**Comment by jnunemaker** [comment]
Can you provide a small script that show how you were using httparty? Perhaps an httparty version number along with ruby version as well? Closing as this is nothing known, but happy to try to help if you can give more details.
