### ISSUE TITLE
Requests for https URI are made as http

### ISSUE THREAD

**Issue by blazingkin** [jnunemaker/httparty#581]
I'm getting API requests denied because they are happening over http instead of https.

My usage looks like this:
`base_uri 'https://api.thing.org/api/endpoint'`

And to get data I'm using:
`self.class.get("/assets?params")`

I've tried specifying port 403 as well, but I cannot get httparty to make an https request.

Thanks.

**Comment by JonMidhir** [comment]
@blazingkin I can look into this but could you post some code to help me reproduce the behaviour?

**Comment by EmilioCristalli** [comment]
@blazingkin  what version of HTTParty are you using?
I wasn't able to reproduce with 0.16.2.
This is what I'm doing, testing with ngrok, both https and http seem to be using the correct protocol:

```ruby
class ExampleHttps
  include HTTParty
  base_uri 'https://a4264c71.ngrok.io'

  def call
    self.class.get("/assets?params")
  end
end

class ExampleHttp
  include HTTParty
  base_uri 'http://a4264c71.ngrok.io'

  def call
    self.class.get("/assets?params")
  end
end

ExampleHttps.new.call
ExampleHttp.new.call
```

**Comment by blazingkin** [comment]
I'm on 0.16.2

The issue ended up being with the backend service and not HTTParty.
Thanks for the testing.
