### ISSUE TITLE
upload file give an error

### ISSUE THREAD

**Issue by metripurari** [jnunemaker/httparty#584]
I am still getting error whle uploading the file

The parameter looks like this
             {"file"=>
           #<ActionDispatch::Http::UploadedFile:0x007ffedaf3e068
          @content_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
         @headers=
         "Content-Disposition: form-data; name=\"attachment[file]\"; filename=\"gstr1-FEB 2018.xlsx\"        \r\nContent-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet\r\n",
         @original_filename="gstr1-FEB 2018.xlsx",
       @tempfile=#<File:/var/folders/c_/t9781sl51gz1yfcf2fqfz6p40000gn/T/RackMultipart20180322-71273-1xq1kos>>,
      "reference_id"=>19}

When I try to upload it through 

        HTTParty.post("#{base_url}?token=#{token}",
                                      body: @params,
                                      detect_mime_type: true
                                      )

It give an error 

      TypeError (no implicit conversion of ActionDispatch::Http::UploadedFile into String)

**Comment by jnunemaker** [comment]
What version of rails? What version of httparty? Could you get a backtrace of the exception? My gut says it isn't detecting `ActionDispatch::Http::UploadedFile` as an uploaded file even though it should. If so, maybe [this line](https://github.com/jnunemaker/httparty/blob/db8df8c58bbb7182fe52c20eb64924b5f3e70ac1/lib/httparty/request/body.rb#L39) is where the conversion is failing?

**Comment by mcls** [comment]
Hi, I just ran into the same issue.

It seems related to the following lines:

https://github.com/jnunemaker/httparty/blob/db8df8c58bbb7182fe52c20eb64924b5f3e70ac1/lib/httparty/request/body.rb#L32-L35

`file?(value)` returns true for `ActionDispatch::Http::UploadedFile`, but when you call `File.basename` on it, it fails with:

```
*** TypeError Exception: no implicit conversion of ActionDispatch::Http::UploadedFile into String
```

**Comment by mcls** [comment]
If it's changed too `File.basename(path)` it would work with both File/Tempfile and ActionDispatch::Http::UploadedFile:

```
(byebug) File.basename(value.path)
"RackMultipart20180327-53658-2lj8b3.jpg"
(byebug) File.basename(Tempfile.new.path)
"20180327-53658-13pgemv"
```

PS: Passing a File/Tempfile directly works, just supported for the ActionDispatch variant:

```
(byebug) x = Tempfile.new
#<Tempfile:/var/folders/19/b59kndv96js71_09xrz9ssdc0000gn/T/20180327-53658-155bkmd>
(byebug) File.basename(x)
"20180327-53658-155bkmd"
(byebug) File.basename(x.path)
"20180327-53658-155bkmd"
```
