### ISSUE TITLE
Time for a version 1.0 release?

### ISSUE THREAD

**Issue by krisleech** [jnunemaker/httparty#586]
We are still on version 0.x which according to semver means "anything may change at any time", maybe it it time for a 1.0 release :smile:

**Comment by jnunemaker** [comment]
Hilarious that this insanely old and stable library isn't 1.0. For some reason I never use 1.0. I don't know if I've ever done it for a project. Probably fear of commitment. I'll consider 1 for the next release. Thanks for bringing it up and prodding me.

**Comment by benlangfeld** [comment]
@jnunemaker Did you decide against adopting semver?
