### ISSUE TITLE
nested properties in body disappearing.

### ISSUE THREAD

**Issue by coreystinson2** [jnunemaker/httparty#587]
Gem version 0.16.1

Produced on a rails server running a Grape API.
Confirmed not to be a problem on receiving Grape API end by sending same body in postman rest client and receiving as expected.

Example request
```ruby
body = {
  "foo" => [{
    "bar" => [{
      "baz" => ["qux", "quux"],
      "quuz" => ""
    }]
  }]
}

HTTParty.post("endpoint", body: body)
```

Receiving end receives only
```ruby
{
  "foo" => [{
    "bar" => [{
      "baz" => ["qux"]
    }]
  }]
}
```

It appears that nested properties are only having their first key and corresponding value(s) sent in the request, everything subsequent to that is simply removed.

Can confirm version 0.13.7 works as expected with all properties present on the receiving end - will post back when I get the time with results on what version is suspected to have introduced this and a corresponding commit for a cause.

**Comment by coreystinson2** [comment]
Versions 0.13.7 to 0.15.7 tested and confirmed for expected behaviour.
Problem suspected to have been introduced in version 0.16.0

**Comment by EmilioCristalli** [comment]
@coreystinson2  I think this was fixed in https://github.com/jnunemaker/httparty/commit/c51cb3e2d7b9a28c75feb1f5dede793160254b66

Can you confirm if you still see the issue with v0.16.2 ?

**Comment by TheSmartnik** [comment]
Yeah, it should be fixed.

Thanks @EmilioCristalli !
