### ISSUE TITLE
How to convert net/http code into httparty.

### ISSUE THREAD

**Issue by mallikarjunece** [jnunemaker/httparty#593]
require 'uri'
require 'net/http'

url = URI("https://example.com")

http = Net::HTTP.new(url.host, url.port)

request = Net::HTTP::Post.new(url)
request["content-type"] = 'multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW'
request.body = "------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"file_content\"; filename=\"FILE_PATH"\r\nContent-Type: application/json\r\n\r\n\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"key\"\r\n\r\nKEY\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"id\"\r\n\r\nID\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW\r\nContent-Disposition: form-data; name=\"sid\"\r\n\r\nSID\r\n------WebKitFormBoundary7MA4YWxkTrZu0gW--"

response = http.request(request)

**Comment by JonMidhir** [comment]
```
require 'httparty'

body = { key: 'KEY', id: 'ID', sid: 'SID' }

response = HTTParty.post('https://example.com', body: { key: 'KEY', id: 'ID', sid: 'SID' })
```

**Comment by TheSmartnik** [comment]
@JonMidhir Thanks for helping out!

@mallikarjunece please address questions like this to StackOverflow.
