### ISSUE TITLE
Case sensitive headers being changed during request 

### ISSUE THREAD

**Issue by theasteve** [jnunemaker/httparty#599]
I'm currently working on a Rails application using `httparty`. The following header works while making a `curl` requests. `curl -X GET -H "AuthDate: 1531403501"` However, when I make the request from rails. I get the following error:

> \"Authdate\":\"1531403501\"}" }, { "error_code": "external_auth_error", "error_message": "Date header is missing or timestamp out of bounds" } ] }

Here is the headers being pass into the request.

```
  def generate_headers
      {
        "Authorization"  => "HMAC-SHA256 api_key='#{@api_key}' signature='#{@signature}'",
        "AuthDate" => @timestamp
      }
   end
```

but as shown in the error, it is changed from `AuthDate` to `Authdate` which causes the error.

**Comment by jnunemaker** [comment]
I don't see any points in httparty where we downcase or capitalize headers. Do you? Is it possible this is something in net/http itself? Could you try a vanilla net/http request and let me know what happens? I generally use dashes between words in headers e.g. Auth-Date.

Closing to keep things tidy but if this is in fact an httparty issue and not something with net/http I'm happy to re-open.

**Comment by kiddrew** [comment]
It's in net/http/header.rb line 18
