### ISSUE TITLE
`HashConversions.to_params` returns ambiguous encoding for some hashes

### ISSUE THREAD

**Issue by harman28** [jnunemaker/httparty#600]
Shared two request bodies below that are notably distinct, but both of which return identical encoding after normalization.

```json
{
  "a": [
    {
      "b": {
        "c": "d",
        "e": "f"
      }
    }
  ]
}
```
```ruby
hash1 = {a:[{b:{c:'d',e:'f'}}]}
encoding1 = HTTParty::HashConversions.to_params hash1
# => "a[][b][c]=d&a[][b][e]=f"
```

```json
{
  "a": [
    {
      "b": {
        "c": "d"
      }
    },
    {
      "b": {
        "e": "f"
      }
    }
  ]
}
```
```ruby
hash2 = {a:[{b:{c:'d'}},{b:{e:'f'}}]}
encoding2 = HTTParty::HashConversions.to_params hash2
# => "a[][b][c]=d&a[][b][e]=f"
encoding1==encoding2
# => true
```

The way to remove this ambiguity is to use numeric indexes for arrays during normalization:
```ruby
encoding1
# => "a[0][b][c]=d&a[0][b][e]=f"
encoding2
# => "a[0][b][c]=d&a[1][b][e]=f"
encoding1==encoding2
# => false
```

I made this change locally, and naturally, this broke a bunch of test cases which do not expect numeric indices in the normalized request. We could update these tests, or alternately we could allow an extra flag to be sent in `options` that would enable numeric indexes.

Is this something we want to take up? If so, I'll raise the PR. If not, please correct my understanding of the issue.

**Comment by harman28** [comment]
@jnunemaker @sandro Could you take a look at this please?

**Comment by EmilioCristalli** [comment]
@harman28  i think this how arrays are usually encoded in query params (probably because that's the way web servers parse it?).

For ex jQuery does the same if I understand the example correctly:
```js
$.param({ a: [ 2, 3, 4 ] }); // "a[]=2&a[]=3&a[]=4"
```
(see https://api.jquery.com/jQuery.param/)

**Comment by EmilioCristalli** [comment]
Thinking a little more about this, wouldn't it cause ambiguity with hashes with numeric keys if you use numeric indexes for arrays?

for example:
```ruby
{
  foo: {
    0: "a",
    1: "b"
  }
}
```
would be normalized as: `foo[0]=a&foo[1]=b`, same as:
```ruby
{
  foo: ["a", "b"]
}
```

**Comment by TheSmartnik** [comment]
Both of the @EmilioCristalli comments are correct here, thanks!
