### ISSUE TITLE
how to increase timeout for DELETE

### ISSUE THREAD

**Issue by asampatoor** [jnunemaker/httparty#607]
I see the timeout is not working properly for the Delete.
I have the following
```ruby
HTTParty.delete(url, headers: headers, timeout: 30)
```
It's actually timing out after 10 seconds and I want it to wait for 30 seconds even though my program will take somewhere around 15-20 seconds. 

Did anyone had this issue?
Please let me know how to go about replacing the default timeout.

**Comment by TheSmartnik** [comment]
Hi, @asampatoor. Sorry for a long reply.
I've tested delete timeout on localhost and everything seems fine.
If the problem is still relevant, can you give me more details? If not, would love to hear what was the problem and how you fixed it
