### ISSUE TITLE
Need support for Mac OS 10.14?

### ISSUE THREAD

**Issue by razertory** [jnunemaker/httparty#613]
I just upgrade my mac os to version 10.14. Something wrong like this. 
```shell
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin18]
```
when I run `rails c` 
```ruby
> response = HTTParty.get('http://api.stackexchange.com/2.2/questions?site=stackoverflow')
objc[4182]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
objc[4182]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```
The [solution](https://blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/) works in `puma` but not in `httparty
` since I till got the result above. Is there any solution for this gem?

**Comment by jnunemaker** [comment]
I don't think there is anything for httparty to do. I'm open to a suggestion if you have one, but this seems more for web servers and depends on your usage rather than something specific to httparty unless I'm misunderstanding.
