### ISSUE TITLE
Feature Request: Ability to send regular form data as multipart

### ISSUE THREAD

**Issue by rahulbdominic** [jnunemaker/httparty#614]
We are trying to call endpoints which require data to be sent as multipart. However the payload itself isnt a file rather just form data. It would be helpful to have the ability to override the automatic file detection and send a request as multipart even if it isnt a file. 

Something like:
```ruby
...
response = HTTParty.post(
    url, 
    body: { multipart: true, not_file_data: { ... } }, 
    headers: other_headers
)
...
```

The current contract feels like it will send your payload as multipart, however the server was rejecting the request. After stepping through the code I realized that it was ignoring the `multipart` because it did not contain a file. What do you think? I could submit a PR to implement the feature if you think its useful.

**Comment by TheSmartnik** [comment]
@rahulbdominic thanks for bringing it up! Completely forgot to add this feature

> What do you think? I could submit a PR to implement the feature if you think its useful.

No worries. I was just working on it. Hope you don't mind that I add it myself

---

One more thing. If we add `:multipart` option to `body`. There won't be a way to differentiate whether you want to send request as multipart or it's just the name of your parameter. A better way would be to add it as a request parameter like so.
```ruby
HTTParty.post(
    url, 
    body: {  not_file_data: { ... } },
    multipart: true,
    headers: other_headers
)
```
