### ISSUE TITLE
Feature Request: Ability to generate multipart for non-file type request

### ISSUE THREAD

**Issue by kkim-sf** [jnunemaker/httparty#620]
I have an api endpoint that accepts 3 different types of data in the **body, file, url, and base64**. The endpoint happens to actually expect the multipart data to be generated regardless of it not being a file type. 

However, from what I saw in the code, the `generate_multipart` method only gets called if the following conditions are met meaning that it only works for the file type.
```
      def multipart?
        params.respond_to?(:to_hash) && has_file?(params.to_hash)
      end
```

I've tried out the rest-client gem, and it looks like the rest-client gem always generates the multipart if the multipart attribute is set to true. However, it seems that the httparty gem doesn't go so far as actually calling the generate_multipart even when multipart is forced.

**Comment by kkim-sf** [comment]
I'm currently calling a local version of the `generate_multipart` to transform the body directly. But it seems hacky and would be nice if multipart: true generates the multipart regardless of it containing a file or not.

**Comment by kkim-sf** [comment]
Upon further inspection of the repo, it looks like the change I'm requesting was merged into master 16 days ago - https://github.com/jnunemaker/httparty/pull/615/files. However, it hasn't made out as a gem yet it seems.

**Comment by TheSmartnik** [comment]
@kkim-sf yes, you're correct a new version hasn't been released yet.

As soon as new version is released, I'll let you know in this issue.
Meanwhile, you can specify in your `Gemfile` to use master branch from github like so.

Gemfile

```ruby
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end
...
gem 'httparty', github: 'jnunemaker/httparty'
```
