### ISSUE TITLE
not parsing json response

### ISSUE THREAD

**Issue by WickyNilliams** [jnunemaker/httparty#631]
I've tried a bunch of things but I simply cannot get a JSON response to be automatically parsed for me. 

This URL returns JSON and `application/json` as the `Content-Type`: https://rubygems.org/api/v1/versions/httparty.json, as can be seen here:

```sh
curl -s -I https://rubygems.org/api/v1/versions/httparty.json | grep "Content-Type:"

# => Content-Type: application/json; charset=utf-8
```

Requesting it:

```rb
response = HTTParty.get('https://rubygems.org/api/v1/versions/httparty.json')
puts response.body.class

# => String
```

Even if I try to force the format, the result is the same:

```rb
response = HTTParty.get('https://rubygems.org/api/v1/versions/httparty.json', format: :json)
puts response.body.class

# => String
```

Am I missing something?

**Comment by WickyNilliams** [comment]
Oh, am I supposed to read from `parsed_response`? I would have expected `body` to be parsed for me

**Comment by jnunemaker** [comment]
@WickyNilliams you can use `response` or `response.parsed_response`. 

For example...

```ruby
response = HTTParty.get('https://rubygems.org/api/v1/versions/httparty.json')
response.each do |item|
  p item 
end
```

... would print out each item in the array of that response.

**Comment by WickyNilliams** [comment]
Ah, perfect, thanks
