### ISSUE TITLE
undefined method detect for ActionController::Parameters

### ISSUE THREAD

**Issue by NormandLemay** [jnunemaker/httparty#632]
With the version 0.16.3 
rails 5.1.6.1
ruby 2.3.8

we got that error

>  undefined method detect for ActionController::Parameters

`{:body=>{:contact=><ActionController::Parameters {"contact_id"=>"", "firstname"=>"dsgf", "lastname"=>"sdfg" "company_name"=>""} permitted: true>, :additional_fields=><ActionController::Parameters {"8"=>{"0"=>"CCT", "1"=>"", "2"=>""}} permitted: true>, :locale=>:en}}`

But all working fine with the version  0.15.7

I found that code into request/body.rb:
`      def has_file?(hash)
        hash.detect do |key, value|
          if value.respond_to?(:to_hash) || includes_hash?(value)
            has_file?(value)
          elsif value.respond_to?(:to_ary)
            value.any? { |e| file?(e) }
          else
            file?(value)
          end
        end
      end
`

**Comment by TheSmartnik** [comment]
Fixed in 0.16.4
