### ISSUE TITLE
Sensitive headers are sent to cross-site when redirecting

### ISSUE THREAD

**Issue by kyoshidajp** [jnunemaker/httparty#637]
Sensitive headers (Authorization and Cookie) are sent to cross-site when redirecting.

For example, an original target URL is http://example.com and redirect to http://example.jp (cross-site). The sample code is the following.

```rb
require 'httparty'

req = HTTParty::Request.new(Net::HTTP::Get, 'http://example.com')
req.options[:headers] = {'Authorization': 'Basic xxx',
                         'Cookie': 'key=value'}
req.perform
```

http://example.jp can get these headers. Actually, I do not think that these headers will be specified at the same time.

**Comment by TheSmartnik** [comment]
@kyoshidajp Thank you for the issue and pr. However, I'm not sure, that's an undesired behavior.

1. That be really counter intuitive, inconsistent and confusing if we delete some headers
2. Probably the site we are being redirected to would need this headers as well. Like `http://example.com` and `http://example.jp` has the same backend, so the same headers would work there as well.

At first, I thought to suggest to an `send_headers_on_redirect` option, but HTTParty already has a ton of options already. I'll close the issue for now, but if the issue will get more attention. I'll happily reopen and reconsider. 

Thanks again for bringing it up.
