### ISSUE TITLE
Encoding Incorrect when Streaming Response

### ISSUE THREAD

**Issue by mvastola** [jnunemaker/httparty#643]
I'm running into an issue where the encoding is not set according to the response HTTP headers when using `:stream_body => true`. 

I've provided a minimal reproducible example in a gist at https://git.io/fhSBB.

In short, if I look at `req.headers['content-type']` I (correctly) see `["text/html;charset=UTF-8"]` and `req.body.encoding` returns `UTF-8`. However, for whatever reason, `fragment.encoding` (`fragment` being the argument to the block provided to `HTTParty.get(URL, :stream_body => true)` ) is `ASCII-8BIT`.

Oddly, it works fine when not using streaming.

I'm happy to help troubleshoot this if there's any way I can be of help.  Any assistance would be appreciated.

**Comment by mvastola** [comment]
Thanks so much!

**Comment by TheSmartnik** [comment]
@mvastola I've finally merged the request. Sorry to keep you waiting.
I'm not yet sure, when the new version of is going to be released. Before that, I suggest to fetch httparty directly from github with the following change in your `Gemfile`

```ruby
gem 'httparty', github: 'jnunemaker/httparty'
```

**Comment by mvastola** [comment]
No worries! Thanks again!
