### ISSUE TITLE
No Method Error for examples/stream_download.rb, code on fragment

### ISSUE THREAD

**Issue by BookOfGreg** [jnunemaker/httparty#645]
https://github.com/jnunemaker/httparty/blob/7b2ad805a5bcc80dc4b06b542dd6de161e5cd95b/examples/stream_download.rb#L14
In HTTParty 0.16.3, this code returns 
```ruby
NoMethodError (undefined method `code' for #<String:0x00007fffc628b450>)
```

**Comment by TheSmartnik** [comment]
@BookOfGreg Hi! `#code` was added to fragment in version 0.16.4, please upgrade

**Comment by BookOfGreg** [comment]
Sorry to use your time on such a daft question. Thank you. :)

**Comment by TheSmartnik** [comment]
@BookOfGreg no worries. Happy to help! 😄
