### ISSUE TITLE
Unable to pass body in with content type application/vnd.api+json

### ISSUE THREAD

**Issue by ayazahmadtarar-pikessoft** [jnunemaker/httparty#650]
I wanted to pass my raw body with `application/vnd.api+json` header it accept the raw body How I can make request with such header type

**Comment by TheSmartnik** [comment]
I think this question best suited for StackOverflow.

Anyway, this should work
```
HTTParty.post(url, headers: { 'Content-Type' => application/vnd.api+json }, body: body)
``
