### ISSUE TITLE
HTTPInternalServerError when sending POST, works in Postman

### ISSUE THREAD

**Issue by c2ofh** [jnunemaker/httparty#652]
I've tried to send a POST-Request, but I recieve a 500 HTTPInternalServerError as response
```ruby
<HTTParty::Response:0x564810bef5b0 parsed_response=nil, @response=#<Net::HTTPInternalServerError 500 Internal Server Error readbody=true>, @headers={"date"=>["Mon, 11 Mar 2019 22:06:24 GMT"], "content-length"=>["0"], "connection"=>["close"], "server"=>["nginx"]}>
```
When I send the request via Postman, I will receive a valid answer after the request.
The Request is very simple.

```ruby
response = HTTParty.post(
   "#{base_url}/#{path}",
   headers: __request_params.merge(params),
   body: payload.to_json
)
```
The Data
```ruby
__request_params.merge(params) 
=> {"Content-Type"=>"application/json", "Authorization"=>"Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjE5NTkyRDA5R...}
payload.to_json
=> "{\"endpointUrl\":\"https://my-domain.com/path\",\"topic\":\"Topic\",\"propertyId\":\"PROP\"}"
```

I've tried to send the hash, plain as ruby hash, and also with `.stringify_keys`, but none of the request works.

**Comment by TheSmartnik** [comment]
@c2ofh everything looks correctly on the surface. I don't think I can reproduce it without concrete URL.

Hit me up by email if you don't want to share private data here

**Comment by pjmartorell** [comment]
Check that you are passing the right parameters. Some endpoints expect that you pass the Accept header `"Accept: application/json"` as well.
You can use `netcat` command to listen on your localhost on a specific port. In example:
`nc -lv 4000`
This will start a process listening everything you request on localhost:4000

Then, define `base_url` as `http://localhost:4000` on your code and make the request and look in the terminal of netcat what are you receiving (headers, body, etc.). Check that everything is as you expected to be.

**Comment by TheSmartnik** [comment]
Closing this since we haven't heard any response in a few months
