### ISSUE TITLE
Response request headers no longer stored in submitted key type

### ISSUE THREAD

**Issue by Touchstone117** [jnunemaker/httparty#654]
Previous behaviour (0.16.2): response request header options were stored with the same key type as they were set in the request

Current behaviour (0.16.4): they are always returned with string keys 

When headers keys are Symbols - behaviour changed
`{ Authorization: 'Bearer' }`

version - 0.16.4
> response.request.options[:headers] - {"Authorization"=>"Bearer"}

version - 0.16.2
> response.request.options[:headers] - {:Authorization=>"Bearer"}

When headers keys are strings - behaviour unchanged
` "Authorization" => 'Bearer'` 

version - 0.16.4
> response.request.options[:headers] - {"Authorization"=>"Bearer"}

version - 0.16.2
> response.request.options[:headers] -  {"Authorization"=>"Bearer"}

Minimum reproduction code.
```
require 'httparty'

puts "HTTParty version - #{Gem.loaded_specs['httparty'].version}"

headers = 
{
  Authorization: 'Bearer'
}

response = HTTParty.get('http://github.com', headers: headers)

puts "response.request.options[:headers] - #{response.request.options[:headers]}"
```

**Comment by TheSmartnik** [comment]
Hi @Touchstone117,

It's an intentional change, we previously had issues with storing headers in both symbols and strings.
See https://github.com/jnunemaker/httparty/issues/629

**Comment by Touchstone117** [comment]
Thanks for the information @TheSmartnik, closing.
