### ISSUE TITLE
Exception being raised when reading http_version on unparseable responses

### ISSUE THREAD

**Issue by slicedpan** [jnunemaker/httparty#655]
When reading the `http_version` of a response, this is delegated to `parsed_response` through a `method_missing` call which raises an exception if the response is not parseable.

**Comment by pjmartorell** [comment]
What is the issue? Raising an exception is not a bug itself, is your responsibility to rescue and recover from an exception if the response is not the expected

**Comment by slicedpan** [comment]
Sorry, just realised I should have been a bit clearer. In my use case, the HTTP response is valid, but the body is not parseable according to the reported content-type. 

Calling `http_version` on such a response throws an exception, even though the HTTP part of the response is valid.

**Comment by pjmartorell** [comment]
If you could post some code and the full trace of the exception, maybe we could see where is the problem

**Comment by slicedpan** [comment]
Hi, I just submitted a pull request. The issue was due to checking the `parsed_response` first in `method_missing`, before checking the `Net::HTTP` response. 

I'm not 100% sure about the spec tbh, it's a bit messy but it seems like it would be hard to write a spec to cover this without pulling apart a lot of the current response spec. Let me know if you have any suggestions.
