### ISSUE TITLE
Performing a tap yields parsed_response instead of Response

### ISSUE THREAD

**Issue by steverob** [jnunemaker/httparty#662]
I'm on `0.13.1` and I'm trying to use `#tap` to refactor my code. But inside the block where the response is supposed to be yielded, I'm receiving the `parsed_response` instead of the Response object itself. Here is a video that shows this: https://imgur.com/ZnqQce3

The `class` of the object is `Array` (response) from within the block:

```
response.tap do |r|
  puts r.class
end
#=> Array
```

How is this even possible?

---
Update:

Upgrading to latest seems to yield proper `HTTParty::Response` when doing `#tap`.

**Comment by TheSmartnik** [comment]
Hi!
Could you please try to reproduce it on the most recent version? `0.13.1` is five years old

**Comment by steverob** [comment]
Works fine in latest. Was just curious how this happens in older versions as tap simply yields the same object.

--
Regards
Steve Robinson

**Comment by TheSmartnik** [comment]
I believe this type of questions are more suited for stackoverflow as it's not a problem with the library any longer. You can look in the [source code of version 0.13.1](https://github.com/jnunemaker/httparty/tree/v0.13.1) to look for yourself how it was implemented.

**Comment by steverob** [comment]
Apologies. Thanks.

Regards
Steve Robinson
