### ISSUE TITLE
Deprecate md5 algorithm

### ISSUE THREAD

**Issue by ioggstream** [jnunemaker/httparty#663]
## I expect

md5 not be used anymore, because it's insecure.

https://github.com/jnunemaker/httparty/blob/99751ac98af929b315c74c2ac0f5ffa09195f7ae/lib/httparty/net_digest_auth.rb#L1

**Comment by TheSmartnik** [comment]
It is used for digest access authentication. We can't stop using MD5 since its part of the implementation

**Comment by ioggstream** [comment]
I suggest at least to  warn that it's NOT RECOMMENDED https://tools.ietf.org/html/rfc7616#section-3.2
