### ISSUE TITLE
SSL_connect returned=1 errno=0 state=error: dh key too small

### ISSUE THREAD

**Issue by marcelolx** [jnunemaker/httparty#664]
Our server runs with DH key size of 2048 bits  and we are trying to make requests with httparty to a server that uses DH key size of 1024 bits, i want to now for what reason we are getting this error `SSL_connect returned=1 errno=0 state=error: dh key too small`, it's because different DH key sizes? 🤔 

We haven't control of the server who are using DH key size of 1048 bits.

How we can handle with this?

**Comment by jnunemaker** [comment]
I wish I could help you, but I'm not sure that this is any problem with httparty and I really don't know much about this topic. If anyone else does, please chime in. Also if you find that it is a problem with httparty please re-open with steps to reproduce. Thanks!
