### ISSUE TITLE
HTTParty doesn't do CGI.escape automatically

### ISSUE THREAD

**Issue by ferdi2005** [jnunemaker/httparty#665]
Hi, in today's internet we can create domains with accents and with emoji, and so we can use accents and emoji in our requests. HTTParty generate an error if we use a non-ASCII character, why doesn't it do `CGI.escape` automatically?

**Comment by TheSmartnik** [comment]
@ferdi2005 Hi, thanks for reporting. I'll fix in the next couple of days and get back to you

**Comment by TheSmartnik** [comment]
@ferdi2005 
`CGI.escape` won't help here. I've just merged a pr that normalizes uri before making a request. To properly handle international domain names, you need [addressable](https://github.com/sporkmonger/addressable)

If you're making single request

```
HTTParty.get(url, uri_adapter: Addressable::URI)
```

In a class
```
class Foo
  include HTTParty
  uri_adapter Addressable::URI
end
```
---
Don't forget to update you Gemfile to include httparty from master branch

**Comment by ferdi2005** [comment]
Perfect, thanks! 🎉

**Comment by ferdi2005** [comment]
Shouldn't you add this to the README? @TheSmartnik

**Comment by TheSmartnik** [comment]
@ferdi2005 yeah. README needs a complete rewrite for a while now, haven't got time to do this, unfortunately
