### ISSUE TITLE
NoMethodError (undefined method `include?' for nil:NilClass)

### ISSUE THREAD

**Issue by ferdi2005** [jnunemaker/httparty#666]
HTTParty raises this very very strange error when doing a simple thing like: `              HTTParty.get(CGI.escape("http://api.telegram.org/bot#{bot_api_key}/sendMessage?chat_id=#{@group.chat_id}&text=Bella zio! Sono il bot asdoso creato da Ferdinando Traversa (ferdinando.me) da idea di Valerio Bozzolan, asd! Digita /grafico per ricevere il link ad un grafico, anche in privato per averne uno personale, asd o /classifca per scoprire cose interessanti. L'impostazione automatica è che io invii il conto degli ASD alla fine della serata, così però ti perdi cose belle come la faccina dell'ASD di mezzanotte. Per modificare questa impostazione, basta digitare /nightsend ed invierò il messaggio di conteggio appena invii un asd"))
`
(«Why do you need to use `CGI.escape`?» See #665 and the “è“ in the URL)

**Comment by TheSmartnik** [comment]
Since closed related https://github.com/jnunemaker/httparty/issues/665
