### ISSUE TITLE
0.17.1 found in changelog but missing on Rubygems.org?

### ISSUE THREAD

**Issue by jesperronn** [jnunemaker/httparty#672]
Hi

according to the changelog there a 0.17.1 version released. But I cannot find it on rubygems.org

is it released? Could you either remove it from changelog or release it, please?

**Comment by TheSmartnik** [comment]
Yeah, sorry. I've pushed the changes to changelog, but haven't released it.

@jnunemaker could please release 0.17.1 🙏 ?

**Comment by jnunemaker** [comment]
Released. @TheSmartnik if you get me your rubygems email I'll add you there. Thanks!
