### ISSUE TITLE
Not URL encoding &

### ISSUE THREAD

**Issue by ferdi2005** [jnunemaker/httparty#673]
`HTTParty.get("https://commons.wikimedia.org/w/api.php?action=query&meta=globaluserinfo&guiuser=#{photoinfo['user']}&format=json", uri_adapter: Addressable::URI).to_a` even with Addressable::URI working returns `[["warnings", {"main"=>{"*"=>"Unrecognized parameter: Restaurant."}}], ["batchcomplete", ""], ["query", {"globaluserinfo"=>{"missing"=>""}}]]`

`photoinfo['user']` is Bellavista Boutique Hotel & Restaurant

**Comment by TheSmartnik** [comment]
@ferdi2005 Hi! You're constructing url string yourself, that's why `&` doesn't get escaped.  Here is working solution.
```
HTTParty.get('https://commons.wikimedia.org/w/api.php', query: { action: :query, meta: :globaluserinfo, format: :json, guiuser: photoinfo['user'] })
```

**Comment by TheSmartnik** [comment]
Please, in the future post questions like this one on StackOverflow. Because It's not an issue with library, but rather incorrect usage of it.

**Comment by ferdi2005** [comment]
Thanks
