### ISSUE TITLE
Diferent body encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by rjurado01** [jnunemaker/httparty#677]
I have this code:

```ruby
response = HTTParty.post(
  prepare_url(),
  headers: generate_headers(),
  body: params.to_json,
  verify: false
)

p response.body.encoding
p response.response.body.encoding
```

Output:

```ruby
#<Encoding:UTF-8>
#<Encoding:ASCII-8BIT>
```

Why encoding is diferent?

**Comment by jnunemaker** [comment]
No way for me to help you with that little of information. If you can provide a full running script and show that it is something in httparty, I'm happy to try to help despite my lack of knowledge of encodings. Closing to keep things tidy, but if you can get a reproducible script we can try to help.

**Comment by rjurado01** [comment]
test that show error:

```
    it 'show error' do
      stub_request(:post, "http://example.com").to_return(
        body: "úbc".force_encoding("ASCII-8BIT"),
        headers: {'Content-Type' => 'application/json; charset=utf-8'}
      )

      response = @klass.post('http://example.com')
      p response.body.encoding # #<Encoding:UTF-8>
      p response.response.body.encoding # #<Encoding:ASCII-8BIT>
    end
```

**Comment by jnunemaker** [comment]
Does this only happen in specs where you are using webmock or whatever to stub the request or does it happen in real life against a real server as well?

**Comment by rjurado01** [comment]
We have detected the issue in a production proyect when we make a request to a external provider.

We have changed from `response.response.body.encoding` to `response.body.encoding` to solve the problem but it looks strange to us.
