### ISSUE TITLE
0.17.2 gem content is broken and not the same as the content of the v0.17.2 tag

### ISSUE THREAD

**Issue by rymai** [jnunemaker/httparty#681]
It looks like the content if the v0.17.2 tag (https://github.com/jnunemaker/httparty/archive/v0.17.2.zip) isn't the same as when inspecting the `0.17.2` gem, especially for the https://github.com/jnunemaker/httparty/blob/v0.17.2/lib/httparty/module_inheritable_attributes.rb file. The file looks as follows in the gem:

```ruby
module HTTParty
  class ModuleInheritableAttributes < Module #:nodoc:
    def initialize(*names)
      attr_accessor *names

      define_method :inherited do |subclass|
        names.each do |name|
          super(subclass)
          subclass.send(:"#{name}=", send(name))

          subclass.class_eval <<-RUBY
            def self.#{name}
              @#{name} = superclass.#{name}.merge(ModuleInheritableAttributes.hash_deep_dup(@#{name}))
            end

            def self.#{name}=(val)
              Thread["httparty_{name"]
            end
          RUBY
        end
      end
    end

    # borrowed from Rails 3.2 ActiveSupport
    def self.hash_deep_dup(hash)
      duplicate = hash.dup

      duplicate.each_pair do |key, value|
        if value.is_a?(Hash)
          duplicate[key] = hash_deep_dup(value)
        elsif value.is_a?(Proc)
          duplicate[key] = value.dup
        else
          duplicate[key] = value
        end
      end

      duplicate
    end
  end
end
```

**Comment by rymai** [comment]
@TheSmartnik Maybe you built the gem locally with in-progress code and mistakenly released it instead of the code tagged `v0.17.2`?

**Comment by tomdev** [comment]
Confirmed we're also running into issues with the 0.17.2 release.

**Comment by TheSmartnik** [comment]
@rymai Oh, sorry. My mistake. Thanks for bringing it up

**Comment by TheSmartnik** [comment]
@rymai @tomdev fixed
1. Removed version 0.17.2 from rubygems
2. Pushed a version 0.17.3

Again thanks for creating the issue and sorry for the inconvenience

**Comment by rymai** [comment]
No problem, this happens! Thanks for the reactivity!
