### ISSUE TITLE
response nil variant

### ISSUE THREAD

**Issue by dvodvo** [jnunemaker/httparty#705]
The application code calls and API ``` @result = HTTParty.post( ``` and handles the response as follows:
```@result['redirectUrl'].present?```
And logging the deprecation message:  [DEPRECATION] HTTParty will no longer override `response#nil?`. This functionality will be removed in future versions. Please, add explicit check `response.body.nil? || response.body.empty?`. For more info refer to: https://github.com/jnunemaker/httparty/issues/568

But changing the code according to the above suggestion to ```if @result.body.present? && @result['redirectUrl'].present? ``` still generates the error.

How should this deprecation error be overcome then?

**Comment by TheSmartnik** [comment]
@dvodvo are you sure the problem is with `@result['redirectUrl'].present?`? Unfortunately, I can't reproduce it. Please double-check the warning message to see the exact location where `nil?` is called

**Comment by dvodvo** [comment]
```.rbenv/versions/2.6.1/lib/ruby/2.6.0/logger.rb:460:in `add'
[DEPRECATION] HTTParty will no longer override `response#nil?`. This functionality will be removed in future versions. Please, add explicit check `response.body.nil? || response.body.empty?`. For more info refer to: https://github.com/jnunemaker/httparty/issues/568``` 
is the message being logged.  Curiously, it is being returned twice around this call
```    Rails.logger.info @result```
