### ISSUE TITLE
True values should be sent as true and not the string version: "true"

### ISSUE THREAD

**Issue by krzkrzkrz** [jnunemaker/httparty#707]
Any reason why

```
class Partay
  include HTTParty
  base_uri 'http://localhost:3000'
end
options = {
  body: {
    foo: true
  }
}
pp Partay.post('/pears', options)
```

Sends the values for `foo` as a string `"true"` instead of a raw `true` value?
That said, is it possible to instruct Httparty to make sure `true` is passed as `true` and not `"true"`?

**Comment by TheSmartnik** [comment]
You can send it as JSON
```
body: {
    foo: true
  }.to_json
```

**Comment by krzkrzkrz** [comment]
I also need to pass `'Content-Type': 'application/json'` header in the request. Thanks for that
