### ISSUE TITLE
Curl logging issue

### ISSUE THREAD

**Issue by Ruslan** [jnunemaker/httparty#738]
https://github.com/jnunemaker/httparty/commit/b8f769e9f3133ec1dfa7fb2800ff3542d4248099#diff-92d721190564ca774f5c7c75580762231de80183232ca8a307e93c3d81111130L25

Seems that newline was single-quoted mistakenly. After upgrade from 0.18.1 to 0.19.0 curl logger returns one-line log. It is not comfortable to read and it can't restored with replace because response data may contain `\n` too

**Comment by jnunemaker** [comment]
Thanks for reporting!
