### ISSUE TITLE
Add created? in docs

### ISSUE THREAD

**Issue by nnat425** [jnunemaker/httparty#741]
Upon using HTTParty, I noticed in our code base we used the method `created?` on a response object. Why isn't the `created?` method included in the documentation?

**Comment by jnunemaker** [comment]
I think it comes from this: https://github.com/jnunemaker/httparty/blob/8ceb806b09d0e14ee5be00804a4fc2ce69eae079/lib/httparty/response.rb#L58-L67

I believe this was added during a break from maintaining. I'm not opposed to adding stuff like this to docs somewhere if that makes sense. Let me know if you have any ideas on a good spot.

**Comment by jnunemaker** [comment]
Oh and here are the specs: https://github.com/jnunemaker/httparty/blob/8ceb806b09d0e14ee5be00804a4fc2ce69eae079/spec/httparty/response_spec.rb#L243-L284
