### ISSUE TITLE
read html response

### ISSUE THREAD

**Issue by sajjadmurtaza** [jnunemaker/httparty#744]
is there any way to read HTML response?

response.body
`=> "<!doctype html>\n\n\n <title>Example Domain</title>\n\n ..."
`
How can I retrieve data from HTML responses?

**Comment by jnunemaker** [comment]
response.body returns the html. I'm not sure I follow what you are asking. Are you want it parsed as a Hash? If so, I'd look at Nokogiri which is great at reading and manipulating xml and html.
