### ISSUE TITLE
Feature - default headers

### ISSUE THREAD

**Issue by danielgomezrico** [jnunemaker/httparty#750]
Hi

It would be nice to have a way to setup HttParty so every request made by HTTParty contains some headers by default.

# Ideas
- Add a setup code that could be run from a rails initializer
- Add some interceptor setup (like interceptors from retrofit on android world https://square.github.io/okhttp/features/interceptors/)

**Comment by jnunemaker** [comment]
> It would be nice to have a way to setup HttParty so every request made by HTTParty contains some headers by default.

I believe that is what [this does](https://github.com/jnunemaker/httparty/blob/86b4d0ce789014d779b744ab4390a4442bfd64d8/lib/httparty.rb#L59). Is that not what you are looking for? Let me know. I'm closing as I think it covers your request, but if I'm wrong let me know and I can re-open.
