### ISSUE TITLE
Add application/problem+json to the supported formats

### ISSUE THREAD

**Issue by nortonbatista** [jnunemaker/httparty#758]
Good evening!

I was using an API and the endpoint returned "application/problem+json" in the Content-Type. I had to create a custom parser
just to make HTTParty parse the response from the API.

Can you guys add this content type in the SupportedFormats?

My custom parser:
```
class CustomParser < HTTParty::Parser
  SupportedFormats.merge!(
    { 'application/problem+json' => :json }
  )
end
```

**Comment by jnunemaker** [comment]
We aren't going to add custom content types, but creating your own parser or manually adding `format: :json` seems right.
