### ISSUE TITLE
file upload support to make http fun

### ISSUE THREAD

**Issue by timwaters** [jnunemaker/httparty#77]
Pretty much every ruby http library does not support file uploads. This is wrong, and leads people to write their own libraries, scripts, subroutines and hacks, often failing. 

Httparty, being the best http library should support this. 

Please make http fun, and support file uploads.

Thanks

**Comment by trkrameshkumar** [comment]
+1

**Comment by icalvete** [comment]
+1

**Comment by ajahongir** [comment]
+1

**Comment by zbeat** [comment]
+1

Years ago, we implemented [HTTMultiParty](https://github.com/jwagener-soundcloud/httmultiparty) as a workaround, and it's been working perfectly ever since. However, as that is an unmaintained project, I'm starting to long for native multipart support in HTTParty.

**Comment by naveengowd** [comment]
By using the RestClient gem we can easily handle the file uploads, but make sure that you install the rest-client gem.

And the code in controller as like below,


      res = RestClient::Request.execute(
          method: :post,
          url: "http://www.your_url.com",
          payload: params,

          headers: {
              'Content-Type' => "multipart/form-data",
              Authorization: "some_key",
              :Accept => "*/*"
          }

      )

**Comment by ntnmrndn** [comment]
Why the close?

**Comment by jnunemaker** [comment]
I explained why in the comment before the close. https://github.com/jnunemaker/httparty/issues/77#issuecomment-5265028

**Comment by sg552** [comment]
Seems this functionality is not supported by HTTParty.  So I turn to RestClient...

**Comment by TorvaldsDB** [comment]
@sg552 So am I ...

**Comment by iamsimakov** [comment]
for future generations:
`HTTParty.post("https://example.com", body: { data: File.new("car.mp4") } )`

)))
