### ISSUE TITLE
Bug in post function

### ISSUE THREAD

**Issue by berti92** [jnunemaker/httparty#775]
Sorry, I couldn't find a better subject.

Our app sends a POST to MS Teams. Every POST triggers a 500 on MS Teams.

I thought Teams had a problem, but I can not explain why the exact same code with net/http works.

As example: Set up an incoming webhook in MS Teams and then send a Post via httparty and then via net/http.

Payload as json:

```
{
    "@type": "MessageCard",
    "@context": "http://schema.org/extensions",
    "themeColor": "C51718",
    "summary": "Test hat zu \"Test\" eine Frage gestellt:"
}
```
The payload is not important, I can't manage to get a working POST to MS Teams in any way with httparty.

I couldn't provide a URL, because we use a private incoming webhook.

I use version 0.21.0 under Ubuntu 22.04 LTS with Ruby 3.1.3

**Comment by jnunemaker** [comment]
I'd be happy to investigate if you can get me a script that shows the bug. Without that, I'm not sure what to do.
