### ISSUE TITLE
csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0

### ISSUE THREAD

**Issue by diei** [jnunemaker/httparty#797]
After update to Ruby 3.3.0 I get following information:

`~/.rvm/gems/ruby-3.3.0/gems/httparty-0.21.0/lib/httparty.rb:10: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec. Also contact author of httparty-0.21.0 to add csv into its gemspec.`

**Comment by wmanica** [comment]
Here for the same reason. Other gems have resolved adding the gems to the gemspec, in this case csv.

here an example: https://github.com/thinreports/thinreports-generator/pull/134/files

**Comment by mishina2228** [comment]
#796 has already been merged, so all that remains is for the new version to be released.

**Comment by jnunemaker** [comment]
Whoops! I thought I released new version. Looks like I forgot. I'll do that now.

**Comment by krystof-k** [comment]
Just an observation regarding this: this possibly breaks using the existing default gem without `require "csv"` for everyone with this gem in dependencies (`uninitialized constant SomeClass::CSV`).

**Comment by wJoenn** [comment]
@krystof-k can you explain how come Rails is not requiring the "csv" gem that is now in our Gemfile like it does with any other gem ? 🤔

**Comment by krystof-k** [comment]
@wJoenn I have no idea. Rails 🪄🎩.
