### ISSUE TITLE
Doc request: please explain which changes in 0.22 are breaking changes

### ISSUE THREAD

**Issue by jaredbeck** [jnunemaker/httparty#801]
Looking at the [0.22 release notes](https://github.com/jnunemaker/httparty/releases/tag/v0.22.0) it's not clear to me which changes are breaking changes.

If there are breaking changes, could you please annotate them?

If not, may I suggest adding a line like "No breaking changes" or "No changes to public API"?

In SemVer, `0.x.x` libraries are allowed to make breaking changes at any time, so documentation like this will be very helpful.

Thanks!

**Comment by jnunemaker** [comment]
Dropping the support for old versions of Ruby was the breaking change.

**Comment by jaredbeck** [comment]
> Dropping the support for old versions of Ruby was the breaking change.

IMHO, that's not a breaking change.

So, if that was the only notable change, I recommend adding a line like "No breaking changes" or "No changes to public API" to the release notes.

Thanks!

**Comment by jaredbeck** [comment]
On a related note, removing the top-level `require`s in https://github.com/jnunemaker/httparty/pull/760 may cause issues for some users who fail to `require` their own dependencies (speaking for a friend 😄 ) For example, if my friend's codebase requires `CSV` but they fail to specify that dependency in any way, then they will see `NameError: uninitialized constant .. CSV` after updating `httparty` to 0.22. This is not a breaking change in `httparty`, but you might choose, in an abundance of compassion, to mention it in the release notes. 😆

**Comment by jnunemaker** [comment]
@jaredbeck it is breaking if you use those versions. That's why I bumped. Most everything else should be pretty stable and has been for years.
