### ISSUE TITLE
Unable to install (older) version of httparty because of dependencies

### ISSUE THREAD

**Issue by tim-briers** [jnunemaker/httparty#805]
I'm experiencing the following issue:

`gem install httparty -v 0.21.0 --verbose
HEAD https://api.rubygems.org/api/v1/dependencies
404 Not Found
GET https://api.rubygems.org/prerelease_specs.4.8.gz
304 Not Modified
GET https://api.rubygems.org/specs.4.8.gz
304 Not Modified
ERROR:  Error installing httparty:
	mini_mime requires Ruby version >= 2.6.0. The current ruby version is 2.5.0.`
	
The dependency packages are installed (higher than required version: https://rubygems.org/gems/httparty/versions/0.21.0):

`gem list | grep -E 'mini|xml'
mini_mime (1.1.2)
multi_xml (0.6.0)`

`ruby -v
ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-linux]`

This is the LTS Ruby version for Rhel8.

I'm not sure why the installation is complaining about the mini_mime version, mini_mime is installed.

Any advice is greatly appreciated!

**Comment by jnunemaker** [comment]
It looks like it's just a ruby version issue. Did you sort that out? mini_mime requires >= 2.6.

**Comment by tim-briers** [comment]
> It looks like it's just a ruby version issue. Did you sort that out? mini_mime requires >= 2.6.

Indeed, i went with Ruby 3.1. 
It was confusing though, because each version should have a different .gemspec file, right? Or do i understand this wrong? I'm not really experienced with Ruby.

But like you said mini_mine requires `spec.required_ruby_version = ">= 2.6.0"` ...and i guess this applied for all versions of that gem on installation?

**Comment by jnunemaker** [comment]
> But like you said mini_mime requires spec.required_ruby_version = ">= 2.6.0" ...and i guess this is checked for all versions of that gem on installation?

Correct. It's out of my hands unless I lock to an older version of mini mime.
